### ISSUE TITLE
Corrupted matrix...

### ISSUE THREAD

**Issue by Radagast** [gorhill/uMatrix#222] opened 2015-05-22 08:19 UTC
First time I've seen this. uMatrix 9.1.1/firefox 38.0.1

![Imgur](http://i.imgur.com/cJMC42c.jpg)

**Comment by gorhill** [comment] 2015-05-22 11:23
Was it after launching the browser? Looks like #56.

**Comment by gorhill** [comment] 2015-05-22 11:24
What is corrupted?

**Comment by gorhill** [comment] 2015-05-22 11:32
I am going to guess you refer to the long hostname, duplicate of #182.

**Closed by gorhill** 2015-05-22 11:32 UTC

**Comment by 5t3f4n** [comment] 2015-05-22 14:58
The problem goes away if you collapse the hostnames (thus truncating the long ones) so gorhill's guess is probably accurate.

![uMatrix](https://i.imgur.com/Wx9RMbR.gif)

**Comment by SergeiShir** [comment] 2016-10-01 22:17
New user of uMatrix
Noticed the same cosmetic issue
![example](https://cloud.githubusercontent.com/assets/17823400/19017316/f947e940-883d-11e6-8a70-2c4ddbc8e62d.png)
