### ISSUE TITLE
Cookie Whitelist Functionality: Allow / Allow Session / Block

### ISSUE THREAD

**Issue by electricessence** [gorhill/uMatrix#449] opened 2015-12-29 22:42 UTC
"Allow" should be obvious: writes and reads cookies, and doesn't delete them.
But if marked as "Allow Session" then it let's cookies be read, but deletes them when the browser closes.
"Block" should also similarly delete when browser closes, or simply doesn't store them at all.  When set to block, it seems silly to store the cookie at all.

**Comment by ldgbc** [comment] 2016-01-03 01:00
Isn't it doing all that already?

The allow-session is controlled via the option, "Delete non-blocked session cookies (x) minutes after the last time they have been used." Unless you want another 3rd option in the uMatrix table that allow all 3 setting rather than the current 2.

Clicking on the "?" in the setting explain it in more depth.

**Comment by Roman-Nopantski** [comment] 2016-01-11 23:53
I think I know what  electricessence is getting at, and I'm all for it as well.

For explanation, I use Cookie Controller ( https://addons.mozilla.org/en-US/firefox/addon/cookie-controller/ ) which allows much more control over cookie settings per domain. IN FF options, by default I block all cookies. Then under a domain I can
- allow
- allow as 1st party only
- allow for session only (do not confuse this with a self-destruction or timer destruction)
- deny

If this sort of control could be added into uMatrix, that would be great. Not sure how you would handle it, since the matrix cells are basically on/off, red/green - maybe the cookie column could be four-state.

Unless I'm missing something here, there is no way to allow a domain via uMatrix to allow a session cookie - its either allow or block.

**Comment by kousu** [comment] 2016-01-22 08:15
@Roman-Nopantski , uMatrix already offers allow and allow-as-first-party-only and deny modes, they're just phrased differently than you're used to:
```
# allow
* domain.com cookie allow
# allow as 1st party only
domain.com 1st-party cookie allow
# deny
* domain.com cookie deny
```
(by the way, getting the "*" cases via the GUI is sorta tricky: you have to click the blue domain name of the site you're on in the top left corner *and switch it to the black `*`" mode, which represents the global scope, and then the (domain.com, cookie) box and click it either to allow or deny. gorhill's matrix GUI is really efficient but it's almost too slick to learn).

**Comment by kousu** [comment] 2016-01-22 08:20
But I am unsatisfied with the cookie handling in uMatrix. I am not sure if this is just because I don't understand how to express what I want or if there's actually something missing, so I am going to explain what I do now and contrast it.

I use [SelfDestructingCookies](https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/) and it has a similar design. It allows all cookies in and out as normal, but deletes them at different times. For each domain, you can:
- (red) -- delete cookies from that domain a short timeout after when you **close all tabs** on that domain
- (yellow) -- delete cookies from that domain a short timeout after you reopen the browser
- (green) -- let the default policy apply: delete when you close the browser if it's a session cookie or when the cookie times out if it has a timestamp on it, or never

Basically, I green sites that I trust that I need to log in to, and leave everything else at red, except for some sites that I flip on and off of, like Facebook, which I yellow. I find yellow more convenient than deleting cookies at the end of a session because it means if I reopen my browser intending to go back to Facebook, it still has me logged in, and in a single day at my desk I can check in with Facebook without having to relogin, but I don't need to idle online on it.
((this is actually a lie; I use [surf](http://surf.suckless.org/) with a custom cookie file that only keeps; but the point stands, there are sites that I use that way and *lots* of people use Facebook just that way))


SDC's green is CC's allow (I don't think SDC has allow-as-first-party), SDC's yellow is CC's allow for session, and SDC's red is a stronger allow-for-session ("allow for tab"). uMatrix's whitelisting is going to be in 1st-party mode generally because that's less clicks than flipping to the global scope before

SDC's Green is analogous to , but yellow and red are not the same as blacklisting: under SDC cookies still work as normal (they are not blocked!), it's just that they disappear faster.

However, I think you can use uMatrix to get the same results, basically: my pattern is "red by default, and green sites I trust explicitly." uMatrix's delete-session-cookies option, if set to 1 minute, is like red-by-default.

Now, uMatrix doesn't have any way to replicate yellow mode, but yellow mode is probably an indulgence anyway: especially with the way mobile browsers try to pretend they aren't restarting all the time, it's better to operate on a per-page/per-site basis rather than per-session, since a session often lasts months.

**Comment by kousu** [comment] 2016-01-22 10:02
Yet I am too unsatisfied with the cookie handling in uMatrix. I am not sure if this is just because I don't understand how to express what I want or if there's actually something missing, so I am going to explain what I do now and contrast it.

Use Case
--------------

I use [SelfDestructingCookies](https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/) and it has a similar design. It allows all cookies in and out as normal, but deletes them at different times. For each domain, you can:
- (Red) -- delete cookies from that domain a short timeout after when you **close all tabs** on that domain (this is a tighter version of CC's allow-session: the session is only as long as you are interacting with the site, not as long as you have the browser in RAM, and with a grace period)
- (Yellow) -- delete cookies from that domain a short timeout after you reopen the browser (this is like CC's allow-session, but with a grace period)
- (Green) -- let the default policy apply: delete it when the cookie says to be deleted (including, possibly, never) (this is like CC's allow)

Basically, I Green sites that I trust and also need to log in to, and leave everything else (even the sites I trust) at Red. I Yellow sites that I flip on and off of, like Facebook. I find yellow more convenient because in a single day at my desk I can check in with Facebook without having to relogin, but I don't need to idle online on it, and the timeout policy means that if I reopen my browser just to go back to Facebook, it still has me logged in.

I think SDC's Yellow mode is an indulgence that I should learn to live without: cookie lifetime should be tied to when you're interacting with a site, not when you're using your computer, especially in light of the way mobile browsers try to pretend they aren't restarting all the time but actually totally are. So there's only Green and Red to worry about.

Problems
-------------
I can't replicate SDC's behaviour in uMatrix, as it is now. In some ways they looks very similar, which is why I am so confused. "Delete non-blocked session cookies" effectively changes the session cookie policy from the old HTTP default of delete-on-process-close (~= SDC's Yellow) to delete-on-page-close (~= SDC's red), but it only applies to *whitelisted* cookies, which contradicts my intuition (and SDC's schema) that force-timing out a cookie is a sort of blacklisting!

I think what it comes down to is:
* SDC Green means I trust the site to set permanent cookies
* SDC Red means I only trust it for session cookies

whereas
* uMatrix Whitelist means I trust the site to set both kinds of cookies
* uMatrix Blacklist means I do not trust the site for any cookies

Suggestions
-----------------

After thinking it through, here is my suggestion. Combine the features of SDC and uMatrix with a tri-state cookies rule:
* Whitelisting: allow permanent cookies (colour in Green or Yellow, or White)
* Greylist: force session cookies (colour in Yellow or Violet, or Grey)
  * that is, any permanent cookies are rewritten to be session cookies
  * ..you'd have to add to your rules parser; right now you only have 'allow' and 'block'; sorry about that.
* Blacklist: block cookies (colour in Red or Blue or Black)

Also, please reword the Dashboard to be easier to interpret (I know about cookies and I still had to re-read "Delete non-blocked session cookies" 3 times at least to figure out what it was saying): 
* Instead of "Delete blocked cookies", make that feature non-optional (why would I want to keep blocked cookies around?) and drop it from the UI.
* Rename "Delete non-blocked session cookies" to "Cookie Timeout"
  * Save the string "Session Cookie" and other technical details for the help popup
    * it's just confusing for those most people who do not know cookies come in multiple flavours but just sort of have this vague anxiety about corporations infecting their computer with data
    * Please do give technical details of what counts as an "interaction" though: is it making a request or keeping a page open?
 * If this isn't already the case, make the timer trigger on closing the last tab from a domain (or that includes content from a domain? I dunno, the former seems like more control, since if you close a site you know its cookies vanish, but the latter fits better with the theme of the matrix controlling subcontent)


If you made this change,
* SDC Green is almost equivalent to uMatrix whitelisting
  * A whitelisted *session* cookie will still be affected by Cookie Timeout. SDC Green'd session cookies will actually last until the end of the process. The difference doesn't matter
* SDC Yellow is uMatrix greylisting
  * Except that I cannot set per-site Yellow mode, but that is a small loss; I can either get by with a longer timeout or with whitelisting but making sure to log myself out or telling the site to log me out after so long)
* Like SDC, after you close the last of a domain's tabs (or maybe, the last tab that contained content from that domain), a timer kicks in; if that domain is not accessed before the timeout, its cookies are wiped. I assume this is pretty much how the current option works?* SDC Red is uMatrix greylisting + Cookie Timeout

**Comment by kousu** [comment] 2016-01-22 10:18
Oh! I just had another idea to chew on. Instead of Cookie Timeout triggering a timer, greylisting could rewrite everything as a permanent cookie with short lifetime (except for permanent cookies with a shorter lifetime), and the lifetime could be pulled from Cookie Timeout. It's not like session cookies are any more private than permanent ones; if anyone is storing sensitive data that should never hit the disk in the cookies they send you they're doing it wrong. This is a much simpler implementation, though it doesn't obviously lend itself to the keep-my-cookies-while-i'm-looking-at-the-site feature.

**Comment by gorhill** [comment] 2016-01-22 13:44
Duplicate of #83.

**Closed by gorhill** 2016-01-22 13:44 UTC
