### ISSUE TITLE
Feature Request: Combining/grouping related sites in popup (Youtube)?

### ISSUE THREAD

**Issue by jimbo1qaz** [gorhill/uMatrix#418] opened 2015-11-21 07:00 UTC
(Firefox 42 on Windows 7 x64)

I normally use uMatrix on default-deny mode. Every time I want to allow a site to display Youtube videos, I have to separately allow youtube.com, ytimg.com, and googlevideo.com. This is made even more inconvenient, because I have to refresh once per site before the next shows up.

This copy-and-paste pattern for managing external sites is both inefficient and dirty, and problematic in practice. For example, if you decide to change your ruleset (for example Youtube changes their video location, or you want to enable/disable cookies), you have to change every single site you have visited.

Can you enable a feature where you can "group" together sets of websites? For example, you can show youtube.com, ytimg.com, and googlevideo.com as a (single, expandable, multiple) row which can be allowed and denied with a single click, (and separately if desired?).

These groups should be defined globally, so the user doesn't need to copy-and-paste the grouping rules for every site visited. The user should be allowed to choose websites to combine, and you could also provide sensible defaults, including Youtube, Soundcloud, etc.

**Comment by gorhill** [comment] 2015-11-21 13:26
Duplicate of #30.

**Closed by gorhill** 2015-11-21 13:26 UTC
