### ISSUE TITLE
The hosts blocking doesn't block anything

### ISSUE THREAD

**Issue by stemy2** [gorhill/uMatrix#782] opened 2017-05-08 19:39 UTC
Hello

When i enable a blocking list, non of the sites wich are in the list is blocked. For example, i still can access to 2girls1cup.com even if i checked "Dan Pollock's hosts files", same problem with any other site on the list. Why does the system looks like so useless ? What have i to do to make it working ?

Thanks.

**Comment by gorhill** [comment] 2017-05-08 20:15
Can't reproduce. You will have to make more effort to report issue.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2017-05-08 20:15 UTC
