### ISSUE TITLE
[Feature Request] Common/DRY contexts/rulesets.

### ISSUE THREAD

**Issue by xlevus** [gorhill/uMatrix#471] opened 2016-01-25 22:27 UTC
tl;dr: It would be nice if you could save small groups of changes to a meta host.

Example:
I visit a website with embedded youtube videos. Currently I can either apply rules to the global context and allow embedded video on every site, or I can apply the rules to all the sites each time I visit them.

Instead, if I could assign these rules to a 'meta' host (e.g. `youtube-embed`) that upon my next visit to a site that includes embedded videos, you can just enable the entire `youtube-embed` host.

**Comment by CrisBRM** [comment] 2016-01-25 23:07
This existed before and was called 'Recipes'. Gorhill removed it. I liked that feature, but I trust that it was removed for a reason.

**Comment by gorhill** [comment] 2016-01-25 23:15
I removed it because it needed to be refactored -- it's issue #30. The refactoring is to make it possible for contributors to provide rulesets which can be imported by users, so that I do not have to maintain these myself.

**Comment by Lunatrius** [comment] 2016-02-06 15:01
Wouldn't an editor similar to `dashboard.html#user-rules` work for this?
```
github-bundle github.com *
github-bundle githubapp.com *
github-bundle githubusercontent.com *
youtube-embed googlevideo.com *
youtube-embed youtube.com *
youtube-embed youtube.com frame
youtube-embed ytimg.com *
```

**Comment by the8472** [comment] 2016-07-06 21:53
Similar issue: https://github.com/gorhill/uMatrix/issues/393#issuecomment-156547112

It's basically a subproblem of the more general case that umatrix does not represent the hierarchy of loads well.

top level site -> frame  -> script -> xhr
top level site -> xhr

Those xhrs could go to to the same domain even though you would only want to allow the top level one but not the one in the frame or vice versa.

For youtube embeds you would want to allow top-level -> frame and frame -> googlevideo.com but not top-level -> googlevideo.com

**Comment by gorhill** [comment] 2017-12-02 23:21
Duplicate of #30.

**Closed by gorhill** 2017-12-02 23:21 UTC
Labels: duplicate
