### ISSUE TITLE
Some Javascript is blocked despite blocking disabled.

### ISSUE THREAD

**Issue by themightyoarfish** [gorhill/uMatrix#817] opened 2017-11-18 23:00 UTC
I am visiting this site:
https://github.com/search?utf8=%E2%9C%93&q=android+file+transfer&type=
(though the specific site shouldn't matter). I disable uMatrix blocking, but I still can't click the `Sort` button. Only disabling the extension completely enables the button. I have no other extensions enabled (the gif notwithstanding).

I should note that uploading an image here on Github has the same problem.

My FF version is 57.0 (64-bit) on OS X.

![umatrix](https://user-images.githubusercontent.com/11613312/32985488-8f5e02ac-ccbc-11e7-8479-3aefffaeffe3.gif)

**Comment by gorhill** [comment] 2017-11-18 23:08
Unable to reproduce. You are not providing exact steps to reproduce.

Did you use the logger o investigate? Did you investigate whether the per-site switches interfere?

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

I will re-open if you provide proper steps to reproduce and I confirm there is an issue with uMatrix.

**Closed by gorhill** 2017-11-18 23:08 UTC
Labels: unable to reproduce

**Comment by gorhill** [comment] 2017-11-18 23:19
Your matrix shows empty script cells. Try to force reload using the browser button with the shift key pressed, to force a bypass of the cache.

**Comment by themightyoarfish** [comment] 2017-11-19 08:35
* Force reloading does not change anything
* A new profile with only uMatrix enabled does not exhibit this behaviour
* My ruleset blocks no domains github makes requests to
* Reloading the page in the logger initially showed only few requests and didn't show any blocked ones, but now suddenly shows many more, and also some blocked google domains. The webpage is now back to working as expected.

I really have no idea, what the issue is, but it turned out I had User-Agent switching enabled which was causing this issue.

Thank you for your time.

**Comment by ArchangeGabriel** [comment] 2017-11-19 12:40
For image uploading, you have to add this to your rules:
```
github.com github-production-user-asset-6210df.s3.amazonaws.com xhr allow
```

I can reproduce your issue regarding sort when I enable UA spoofing, because GitHub disables a lot of features if your browser is “too old” (I’ve just had IE as UA, even got a banner about my browser being obsolete).
