### ISSUE TITLE
"Show the number of distinct requests on the icon" stops working

### ISSUE THREAD

**Issue by puff-m-d** [gorhill/uMatrix#514] opened 2016-03-02 21:20 UTC
Hello,

This issue was not present in version 0.9.3.1 but has appeared on the latest released version 0.9.3.3 on Chrome 50.0.2657.3 dev-m (64-bit).

Issue:
The "Show the number of distinct requests on the icon" stops working when refreshing web pages.
![2016 03 02_16h08m22s_002](https://cloud.githubusercontent.com/assets/8797546/13475502/5901afb0-e091-11e5-8d67-6402cb43cc71.jpg)
I noticed this as I frequent a lot of forums and I usually keep tabs open and just go back to the tab and refresh it to see if there is anything new on the page.

Steps to reproduce:
Go to any web page. Refresh/reload the page. It usually first appears on the second refresh but I have also seen it on the first or third refresh. Once it appears, it remains on subsequent refreshes. This happens on almost all web pages that you try it on but there are some web pages that it does not occur on. I have seen it happen on approximately 90 % of the web pages that I tested it on. The screenshot is from this address: https://forums.malwarebytes.org/

If any more information is needed, please feel free to ask. Thanks...

**Comment by gorhill** [comment] 2016-03-02 21:33
Duplicate of #513.

**Closed by gorhill** 2016-03-02 21:33 UTC
