### ISSUE TITLE
Rules set in Chromium incognito mode remain in normal

### ISSUE THREAD

**Issue by t33rex** [gorhill/uMatrix#865] opened 2017-12-04 00:28 UTC
I think it makes sense to work similar to uBO where rules set in incognito are only for the incognito session.

**Comment by gorhill** [comment] 2017-12-04 01:50
Duplicate of #350.

uBO does not work differently.

**Closed by gorhill** 2017-12-04 01:50 UTC

**Comment by t33rex** [comment] 2017-12-04 10:04
> uBO does not work differently.

If I set a rule in uBO while in incognito mode and then close the incognito mode the rule does not show up in "My rules" of uBO, i.e. it does not propagate from incognito to normal. This report suggests that it would be good to be able to set incognito-only volatile rules as it is currently possible for uBO.

I hope that clarifies.
