### ISSUE TITLE
scope changes when downloading files served on different domains

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [gorhill/uMatrix#399] opened 2015-10-29 08:22 UTC
Firefox 41.0.1
uMatrix 0.9.3.0

main case: if sent a file via facebook chat, the file is served from https://cdn.fbsbx.com/*. clicking the file works as most downloads do, the browser gets the file and offers you to save it but the page stays the same. the address bar still shows facebook.com. but umatrix's scope changes to fbsbx.com. the page is still facebook.com but everything is now broken (xhr etc) because umatrix things the page is now on fbsbx.com.

this happens pretty much on any other website where downloads are on different domains. i have to refresh the page for umatrix to get the right scope again.

edit: i will provide a test case in a second

**Comment by berrythesoftwarecodeprogrammar** [comment] 2015-10-29 08:25
test case: https://berr.yt/umatrix.php
it provides a link to the latest umatrix xpi. once downloading, the scope for my site changes to a github amazonaws url

**Comment by gorhill** [comment] 2015-10-29 12:04
Duplicate of #395.

**Closed by gorhill** 2015-10-29 12:04 UTC
