### ISSUE TITLE
Drop-down flips up

### ISSUE THREAD

**Issue by richardh9935** [gorhill/uMatrix#710] opened 2017-02-06 22:32 UTC
Dear uMatrix,
Over the past few months, when I tell uMatrix to drop down, it drops down and immediately (0.5sec) flips back up half-way, thus hiding the top part of the list of items.  

On sites with a full-width banner or menu which is fixed, and where the rest of the site appears to scroll under the fixed banner, I can scroll down a bit and then uMatrix often drops down properly.

This happened with Andryou's ScriptSafe, too, in 2015, but I can't find his GitHub records of that.

Circumstances:
Google Chrome 55.0.2883.95 (64-bit) on MacOs Sierra 10.12.2 (16C67).
Chrome extensions: Avast, Beeline Reader, Bookmark Manager, Google (Dictionary, Docs, Docs Offline, Drive, Inbox, Keep, Sheets, Similar Pages),  OpenDyslexic, Tampermonkey, TextMode, MyWot, Send from Gmail, uBlock Origin, uMatrix, Vanilla cookie manager, Website Informer).
Not all sites.  GitHub site did it seconds ago.

Suspicions:
1. I have conflicting Chrome Extensions.
2. Something in the site rendering conflicts with uMatrix.

My Response:
I will re-test with all extensions OFF.

**Comment by alexanderschnitzler** [comment] 2017-02-08 16:27
I have that issue as well.

See this example screenshot.
<img width="462" alt="screen shot 2017-02-08 at 17 26 39" src="https://cloud.githubusercontent.com/assets/711459/22746389/d753f44a-ee23-11e6-9d38-1fdb16d09ab8.png">

**Comment by gorhill** [comment] 2017-02-08 17:43
Duplicate of #694.

**Closed by gorhill** 2017-02-08 17:43 UTC
