### ISSUE TITLE
Export / Import config found under "about" instead of "settings"

### ISSUE THREAD

**Issue by alexara** [gorhill/uMatrix#562] opened 2016-06-01 10:34 UTC
Hi!

Currently the "backup", "import" and "reset to default" are found under "about".
This does not make much sense. From a contextual point of view they belong under "settings" as it is already the case at uBlock Origin.

Alex

P.S. For uMatrix doesn't exist an issue template yet?

**Comment by gorhill** [comment] 2017-11-20 19:07
Duplicate of #330.

**Closed by gorhill** 2017-11-20 19:07 UTC
Labels: duplicate
