### ISSUE TITLE
adding 3rd party filer lists block everything

### ISSUE THREAD

**Issue by orodeshah** [gorhill/uMatrix#428] opened 2015-12-07 15:59 UTC
- when I add 3rd party filter lists (for example easylist) , all websites are blocked, why ? it means maybe umatrix blocks all hosts mentioned in easylist 
(it happens despite ublock origin, because I am using the same filter list in ublockorigin and only ads are blocked, not whole domain)
-----------
in httpswitchboard wki you had provided kind of set up for using i as ad blocker, but it is removed now, can you present such a thing for umatrix too ?

**Comment by gorhill** [comment] 2015-12-07 16:16
EasyList is not a hosts file. If you feed uMatrix random stuff, it's behavior will be undetermined.

Duplicate of #213.

**Closed by gorhill** 2015-12-07 16:16 UTC

**Comment by Geremia** [comment] 2017-03-14 15:11
@orodeshah See [the Perl script here]() for converting [EasyList](https://easylist.to/easylist/easylist.txt) to a hosts file.
