### ISSUE TITLE
Cropped windows on chrome

### ISSUE THREAD

**Issue by amithiel** [gorhill/uMatrix#723] opened 2017-03-06 16:58 UTC
Hello. This bug is still around...
Software used:

- MacOS Sierra
- Google Chrome version 56.0.2924.87 (64-bit)
- Other extensions: 1password 
- Umatrix version  0.9.3.6

For testing i think there's no better place than porn sites. So i used pornhub. 
After fully loaded, i clicked the umatrix icon, and the window is cropped:

[screenshot](https://s21.postimg.org/prkq1hpl3/Screen_Shot_2017_03_06_at_16_46_53.png)

if you insist clicking again and again and again, sometimes the window shows up normal, sometimes cropped. Similar to what someone posted 2 years ago:

[Gif](https://cloud.githubusercontent.com/assets/8460502/22499884/91844108-e861-11e6-8f78-5a3cbf30f765.gif)

Since i don't have any other extension (besides 1password), i can't think of any incompatibility

**Comment by ddraws** [comment] 2017-03-06 17:40
Duplicate of https://github.com/gorhill/uMatrix/issues/694

**Closed** 2017-03-06 18:00 UTC
Labels: duplicate
