### ISSUE TITLE
uMatrix breaks Google twofactor authentification even if deactivated

### ISSUE THREAD

**Issue by Nanority** [gorhill/uMatrix#833] opened 2017-11-23 10:08 UTC
Hello!

I am using uMatrix 1.1.10 on Firefox 57 and encounter complications to log into my Google account using its two-factor authentication with my cellphone. The corresponding Google tools report a timeout (see screenshot).
The problem occurs regardless of me allowing all scripts and even if uMatrix is deactivated by its internal switch. The login is only working if I disable uMatrix in the Add-ons menu of Firefox.

Just to clarify: my usual login-procedure requires to confirm a notification on my cellphone to proceed with the login.

I would be glad if the problem could be fixed.

Regrads, Nanortity

![screenshot](https://user-images.githubusercontent.com/33927218/33167636-749d55b4-d03e-11e7-916f-e30cdb8dac9a.png)

**Comment by gorhill** [comment] 2017-11-23 12:28
Did you look at the logger? You still have a switch on in the per-site switch. I will be closing because as asked in CONTRIBUTING, you are not making the case the issue is with uMatrix, otherwise you would have made the case the logger does not report anything blocked. Re-open when you make a better case.

**Comment by Remu-rin** [comment] 2017-11-23 12:28
Your screen shows you have one of per-scope switches enabled for that page. Try disabling it. https://github.com/gorhill/uMatrix/wiki/Per-scope-switches
Disabling the matrix only disables filtering, not other features.

**Closed by gorhill** 2017-11-23 12:28 UTC
Labels: invalid

**Comment by gorhill** [comment] 2017-11-23 12:57
Using the logger is really key here. I had a case myself where I had mistakenly enabled matrix filtering in the behind-the-scene scope and this was causing cookies to be deleted (I block cookie globally in uMatrix), and I was unable to log in into Twitter until eventually I saw the cookie deletion in the logger (the ability to see what rule caused something to be blocked/delete is sorely missing in the logger, hopefully I will find the time to addres this eventually).

**Comment by bjoe2k4** [comment] 2017-11-25 21:40
`referrer-spoof: google.com false` does the job with Google 2FA. (in combination with a few script and cookie allows)
