### ISSUE TITLE
UA spoofing is not complete

### ISSUE THREAD

**Issue by crssi** [gorhill/uMatrix#564] opened 2016-06-03 07:01 UTC
Dear mastermind gorhill (in a good sense :))
I have to say I really admire your work and your contribution to the community.
OK, back to issue:
The UA spoofing is not complete, that sad some or all of the following preferences are not set by your UA spoofing method (this is sample and notice that I might have missed some):
user_pref("gecko.buildID", "20160502172042");
user_pref("gecko.mstone", "46.0.1");
user_pref("general.appname.override", "Netscape");
user_pref("general.appversion.override", "5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36 OPR/30.0.1835.49");
user_pref("general.buildID.override", "");
user_pref("general.oscpu.override", "");
user_pref("general.platform.override", "Win32");
user_pref("general.useragent.override", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36 OPR/30.0.1835.49");
user_pref("general.useragent.vendor", "Opera Software ASA");
user_pref("general.useragent.vendorsub", "");

You can check the "Random Agent Spoofer", where those preferences are set when UA spoofing is enabled.

You can see more, if you go to:
https://whoer.net/
scroll down an click big green button "Use extended version"
find section "Navigator"
pay attention to the following attributes: oscpu,vendor,vendorSub,productSub,cookieEnabled,buildID,serviceWorker,appCodeName,appName,appVersion,platform,userAgent,product

I am sure you will know what I mean... try it without and with "Random Agent Spoofer".

Is there any way that you would extend UA spoof functionality?
Do you need any help in a collecting the right data for different UA? If so, let me know, will do the homework to ease at least that part for you.

Thank you in advance
your admirerer

**Comment by d-kr** [comment] 2016-06-03 09:59
Already discussed a few times:

#271 

 with the same website to play with around.

**Comment by crssi** [comment] 2016-06-03 10:31
Oh... sorry, now I feel stupid. ;)

**Comment by gorhill** [comment] 2016-06-03 12:34
Duplicate of #455.

**Closed by gorhill** 2016-06-03 12:34 UTC
