### ISSUE TITLE
js-apps aren't working

### ISSUE THREAD

**Issue by jhsagl4a** [gorhill/uMatrix#396] opened 2015-10-26 10:45 UTC
This https://uprootlabs.github.io/poly-flif/
and this https://s3-us-west-2.amazonaws.com/clickerheroes/ancientssoul.html (need save's codes)
is not working when uMatrix turned on at about:addons menu, even if all filters in uMatrix are turned off.

**Comment by gorhill** [comment] 2015-10-26 12:35
>  https://uprootlabs.github.io/poly-flif/

Works fine here.

You are not providing any details, thus marking as _invalid_ as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Comment by jhsagl4a** [comment] 2015-10-26 14:26
Sorry, I forgot about it.
Firefox 41.0.2. But at previous versions it doesn't work either.

**Comment by gorhill** [comment] 2015-10-26 15:22
What version of uMatrix?
What do you mean with "all filters in uMatrix are turned off"?

**Comment by jhsagl4a** [comment] 2015-10-26 18:34
Last version 0.9.2.1
That mean button which is signed "Disable/еnable matrix filtering for this scope" is pressed, and whole matrix is green.

**Comment by gorhill** [comment] 2015-10-26 19:08
I tried again with uMatrix 0.9.2.1, enabled or disabled, and <https://uprootlabs.github.io/poly-flif/> worked fine. What does not work _exactly_?

**Comment by jhsagl4a** [comment] 2015-10-27 04:33
Oh, I understand now! Now you will can reproduce it!
See, I have a rule:
* * script block
If you will make that rule and reset the browser (Firefox), https://uprootlabs.github.io/poly-flif/ won'l be working (and that is correct). But if you will add a temporary rule with matrix-menu like 
uprootlabs.github.io 1st-party script allow
or
uprootlabs.github.io * script allow
It is not working either (and that is incorrect)! But if will make this rule to become a permanent one, and reset the browser - app will be working now.
I am sorry for my English, it is not my native language.

**Comment by gorhill** [comment] 2015-10-27 04:43
> `* * script block`
> `uprootlabs.github.io 1st-party script allow`
> `uprootlabs.github.io * script allow`

Still works fine.

Are you refreshing the web page after you add the `uprootlabs.github.io * script allow` rule?

**Comment by jhsagl4a** [comment] 2015-10-27 04:51
>Are you refreshing the web page after you add the `uprootlabs.github.io * script allow` rule?
Yes. But app works only after making that rule to get permanent and reset the browser.
Try to add only one rule
`* * script block`
not all three at the same time. If you make all three rule at the same time bug will not reproduce.

**Comment by gorhill** [comment] 2015-10-27 13:12
> not all three at the same time

I am difficulty following you. Let's keep it simple, give me a screenshot of the matrix while you are on the site when you say it does not work while you think it should.

**Comment by jhsagl4a** [comment] 2015-10-27 15:33
![umatrix bug](https://cloud.githubusercontent.com/assets/15322618/10762690/460e214e-7cf1-11e5-8ab5-486aa0e9632d.png)
Ok, with that it does not work.
step one. I only one important (for this bug) rule have `* * script block`
app does not work (of course)
Step two. I have added one temporary rule `uprootlabs.github.io 1st-party script allow` reload page and app does not work either (it is that bag)

**Comment by gorhill** [comment] 2015-10-27 16:01
It does not matter that a rule is permanent, uMatrix will always use temporary rules to evaluate the fitlerin matrix. I still cannot reproduce with your description. I have all temporary rules in my matrix, and it shows 4 scripts and 1 css. Yours is 3 scripts and 1 css. If I actually use the "app", i.e. select an image, there are 2 XHR, which do not appear in your matrix. Something else is blocking these networks requests, since uMatrix is not reporting them. Look at uMatrix logger and see what is reported in there.

**Comment by gorhill** [comment] 2015-10-27 16:09
I am starting to wonder that you are mistaken about teh site not working. You have to select an image before starting to use the applet.

**Comment by gorhill** [comment] 2015-10-27 16:12
By the way, according to the screenshot you posted, you did **not** reload the page: I get exactly what you have in the screenshot if I allow 1st-party script but do not reload the page.

**Comment by gorhill** [comment] 2015-10-27 16:20
Hmm never mind, for some reasons now I can reproduce. Not sure what happens that I can now reproduce, I will investigate. According to the logger, `inline script` is no longer reported, so it appears the page is now using some cached response header with the CSP set to block inline scripts.

**Comment by gorhill** [comment] 2015-10-27 16:45
Alright I am back to being unable to reproduce. Above may have occurred after I re-installed another version of uMatrix and reload the page.

I would like other users to try to reproduce.

**Comment by jhsagl4a** [comment] 2015-10-27 16:46
This bug appers only if I reload page (after I change the rule) with firefox interface.
If I reload page with reload-button on uMatrix-menu, app works.

**Comment by gorhill** [comment] 2015-10-27 16:51
> This bug appers only if I reload page (after I change the rule) with firefox interface.

Ok, now I can reproduce at will.

**Comment by jhsagl4a** [comment] 2015-10-27 16:53
>Look at uMatrix logger and see what is reported in there.
When I reproduced this bug, logger gave me that
![umatrix bug2](https://cloud.githubusercontent.com/assets/15322618/10765532/67d90512-7cfd-11e5-83b9-4e6bbf704b5f.png)

**Comment by jhsagl4a** [comment] 2015-10-27 16:58
![umatrix bug3](https://cloud.githubusercontent.com/assets/15322618/10765684/1f1a39b2-7cfe-11e5-85ac-df8b7c65074d.png)
and this after I reload with reload-button on uMatrix menu (above the red line), it works now

**Comment by gorhill** [comment] 2015-10-27 16:59
> When I reproduced this bug, logger gave me that

So when using FF interface to reload, `flif.js` is not reported to uMatrix's HTTP observer. `flif.js` is creating dynamically by an inline scrip tag on the page.

Using <kbd>Shift<kbd>-reload makes the page reload properly.

Investigating.

**Comment by gorhill** [comment] 2015-10-27 17:11
Ok I think I understand what is going on.

When FF cache the main document, it will also cache the **modified** headers, not the original ones. uMatrix only add CSP directives, it never removes CSP directives, so this mean that uMatrix's previously inserted CSP directive has been cached by Firefox, but uMatrix won't remove it because it should not lower whatever CSP may have been set by a web site -- uMatrix has no way to know that a specific CSP directive in the header is one it inserted itself at some earlier time.

Not sure what can be done for this one.

**Comment by jhsagl4a** [comment] 2015-10-27 17:19
Anyway, I am very glad we understood each other now.

**Comment by jhsagl4a** [comment] 2015-10-31 07:54
Also, you could delete the label `unable to reproduce` because you know, you can do it now.

**Comment by gorhill** [comment] 2017-11-20 18:46
Fixed with fix to #819.

**Closed by gorhill** 2017-11-20 18:46 UTC
