### ISSUE TITLE
Firefox: first time opening a new tab, the matrix is empty and not displaying properly

### ISSUE THREAD

**Issue by gorhill** [gorhill/uMatrix#189] opened 2015-05-12 17:01 UTC
After closing and opening one or  couple more new tabs, the matrix displays correctly.

![a](https://cloud.githubusercontent.com/assets/585534/7593283/f766ab7a-f8a6-11e4-9dfa-b2e0fa1060cc.png)

There should at least be a header row.

**Comment by tlu1024** [comment] 2015-05-12 17:09
Not on my system:

![newtab](https://cloud.githubusercontent.com/assets/1099173/7593424/55a03e30-f8da-11e4-8a71-9817f11b6a1e.png)

**Comment by gorhill** [comment] 2015-05-12 17:10
It will eventually display correctly after you close the first one (repeat if it doesn't). Was it the first new tab you opened?

**Comment by 5t3f4n** [comment] 2015-05-12 17:32
I cannot reproduce. Can you specify the required steps?
Does it matter what your about:newtab URL is? Do the new tabs have to come from clicking a link on another page or something?

`uMatrix 0.9.0.0 (release)`
`Firefox 38.0`
`OS X 10.10.3 (14D136`

**Comment by tlu1024** [comment] 2015-05-12 17:33
> Was it the first new tab you opened?

Yes!

**Comment by gorhill** [comment] 2015-05-12 17:37
It happens when I click the `+` tab to create a new tab. It doesn't matter how long after I launch the browser (I believe), it happens systematically the first time I create a new tab.  I did see this prior to release, but I do not consider this a showstopper. Needs to be fixed though.

**Comment by gorhill** [comment] 2015-05-12 17:41
Ok I think I see how it happens, it's after **installing** or disabling and **enabling** uMatrix. So a edge case, but something I do often on my side during development.

**Comment by tlu1024** [comment] 2015-05-12 17:42
As already said, I haven't seen this in my system (FF 37.0.2).

**Comment by Blutgang** [comment] 2015-05-12 18:22
Tends to happen (rarely) when opening a new tab (not the first new tab I opened). Hard to reproduce consistently. `Firefox 37.0.2`
![umatrix](https://cloud.githubusercontent.com/assets/4369039/7594756/d15359d8-f8b0-11e4-999b-963b6eef1283.png)

**Comment by gorhill** [comment] 2015-05-12 19:36
Systematic:

1. Close all _New tab_ tabs if any opened
1. Go to `about:addons`
1. Disable uMatrix
1. Enable uMatrix
1. Create a new tab by clicking the _Open a new tab_ button
1. Matrix is void -- there should be at least the matrix header row

**Comment by 5t3f4n** [comment] 2015-05-12 20:01
Still can't reproduce. Tried disabling all other extensions and changing my `browser.newtab.url` back to the default `about:newtab` too. Was this accidentally fixed with Firefox 38.0 or what?

**Comment by gorhill** [comment] 2015-05-12 22:30
> Was this accidentally fixed with Firefox 38.0

I could reproduce it with Nightly.

**Comment by dboshardy** [comment] 2015-05-12 22:31
I am on chrome and the window looks like this persistently.  It never displays correctly.  Clicking the buttons doens't do anything, the matrix is never shown.

**Comment by gorhill** [comment] 2015-05-12 22:33
@dboshardy The issue here was definitely on Firefox. Your issue may be related to #194. Provide information in there, like your browser version, etc. I've tested the extension with Chromium 41 and it works fine.

**Comment by dboshardy** [comment] 2015-05-12 22:34
@gorhill, awesome, thanks!

**Comment by gorhill** [comment] 2015-05-13 00:01
OK I pushed a new version to the Chrome store, might take an hour os so before it becomes live -- hopefully it won't be marked as "pending review" (this has been happening randomly lately).

**Comment by Blutgang** [comment] 2015-05-13 03:39
The six step process by Raymond was fixed. However, I still see this issue when opening a new tab. `Firefox 38.0` `uMatrix 0.9.0.1`
![umatrix](https://cloud.githubusercontent.com/assets/4369039/7603199/0e008594-f8fd-11e4-9d7c-e65bf6edf122.png)
(Not sure if this is related) Browser console: `TypeError: matrixSnapshot.userSettings is undefined popup.js:76:4`

**Closed** 2015-05-13 17:28 UTC
Labels: firefox
