### ISSUE TITLE
Problem with long domain names

### ISSUE THREAD

**Issue by beerisgood** [gorhill/uMatrix#650] opened 2016-10-23 17:29 UTC
I found a bug with long domain names:
https://anonmgur.com/up/f5fc5edd6455efd9750825fc888af8df.png

test site: http://www.amonamarth.com/tour-dates

uMatrix 0.9.3.6 - Pale Moon 27 x64 beta 2 - but bug exist a long time, even before Pale Moon 27

**Comment by gorhill** [comment] 2016-10-23 17:44
Duplicate of #182.

**Closed by gorhill** 2016-10-23 17:44 UTC
