### ISSUE TITLE
script-src issue on Firefox

### ISSUE THREAD

**Issue by mweinelt** [gorhill/uMatrix#667] opened 2016-11-21 01:02 UTC
The following is the status page of an embedded router based on https://github.com/freifunk-gluon/gluon, which is based on OpenWrt/LEDE, and of which there are more than 30.000 in Germany.

http://[2001:67c:2ed8:6100:ea94:f6ff:fed4:5a3e]/

It doesn't load with uMatrix 0.9.3.6 on Firefox Nightly (53.0a1) and complains as follows:

```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'unsafe-eval' *”).
```

There is no way to allow the site to load but disabling uMatrix for the complete scope.

![](http://i.imgur.com/8K9byHV.png])

**Comment by gorhill** [comment] 2016-11-21 13:47
I get no issue here using an IPv6 address. Did you try to toggle the per-site switches?

**Comment by gorhill** [comment] 2016-11-21 13:59
Never mind, this is a duplicate of #597, fixed in dev build.

**Closed by gorhill** 2016-11-21 13:59 UTC
Labels: unable to reproduce

**Comment by mweinelt** [comment] 2016-11-21 14:04
huh, ok. for completeness sake here is what I tried and didn't work.

!(logger)[http://i.imgur.com/wZUsMiY.png]
!(not working)[http://i.imgur.com/NaMugYf.png]

**Comment by gorhill** [comment] 2016-11-21 14:29
It didn't work because the issue has nothing to do with rules, it's a Firefox-specific issue which has been fixed in dev build. You can install the dev build from AMO.
