### ISSUE TITLE
uMatrix loses current site scope when opening links in new tabs

### ISSUE THREAD

**Issue by vzjrz** [gorhill/uMatrix#395] opened 2015-10-24 20:58 UTC
Example:
New firefox 41.0.2 profile, uMatrix 0.9.3.0rc2, default settings
~~Go to https://www.monoprice.com/product?c_id=109&cp_id=10904&cs_id=1090407&p_id=13778&seq=1&format=2
uMatrix correctly identifies the scope as www.monoprice.com
Right click on any of the small image thumbnails to open up a new tab for the image
Go back to original www.monoprice.com tab and notice uMatrix now thinks the scope is images.monoprice.com~~
https://jsfiddle.net/vu4fvn8w/embedded/result/

**Comment by skibbipl** [comment] 2015-10-25 08:51
Yep, I have similar issues using self hosted tt-rss instance. When I open rss feed links in new tabs uMatrix looses scope.

**Comment by gorhill** [comment] 2015-10-25 10:10
I am not able to reproduce using FF 41.0.2.

A similar issue was fixed with uBO ([issue 248](https://github.com/gorhill/uBlock/issues/248)), but this one I could reproduce. Being able to reproduce the problem here is important as this would allow me to import the fix from uBO, and to confirm it works.

**Comment by vzjrz** [comment] 2015-10-25 11:07
Can you see it here: https://jsfiddle.net/vu4fvn8w/embedded/result/
You'll need to whitelist `jshell.net` frames

**Comment by CrisBRM** [comment] 2015-10-25 19:12
Can repro.

Rules: 
```
https-strict: 4chan.org true
referrer-spoof: 4chan.org false
* boards.4chan.org script allow
4chan.org * plugin allow
4chan.org * script allow
4chan.org 1st-party cookie allow
4chan.org 1st-party css block
4chan.org 1st-party image block
4chan.org 1st-party other block
4chan.org 1st-party xhr allow
4chan.org 4cdn.org xhr allow
4chan.org 4chan-ads.org * block
4chan.org boards.4chan.org script inherit
4chan.org google.com css block
4chan.org google.com frame allow
4chan.org google.com image block
4chan.org google.com other allow
4chan.org google.com xhr allow
4chan.org googlevideo.com other allow
4chan.org googlevideo.com plugin allow
4chan.org gstatic.com plugin block
4chan.org i.4cdn.org other allow
4chan.org i.ytimg.com plugin allow
4chan.org s.4cdn.org script inherit
4chan.org s.youtube.com plugin allow
4chan.org s.ytimg.com plugin allow
4chan.org s.ytimg.com script allow
4chan.org www.google.com image allow
4chan.org www.google.com script inherit
4chan.org www.youtube.com * allow
4chan.org www.youtube.com cookie block
4chan.org www.youtube.com frame allow
4chan.org www.youtube.com other block
4chan.org www.youtube.com plugin allow
4chan.org www.youtube.com script allow
4chan.org www.youtube.com xhr allow
4chan.org ytimg.com * allow
4chan.org ytimg.com cookie block
4chan.org ytimg.com frame allow
4chan.org ytimg.com other block
4chan.org zkcdn.net * block
```

https://boards.4chan.org/g/

Check the matrix and look at the scope.
Middle click on an image to open it in a new tab.
Scope will go from 4chan.org to 4cdn.org.

**Comment by CrisBRM** [comment] 2015-10-26 16:56
Ugh, it applies to hyperlinks as well.

**Comment by gorhill** [comment] 2015-10-26 17:31
> Can you see it here: https://jsfiddle.net/vu4fvn8w/embedded/result/

Yes, this I can repro. For whatever reason, any scenario which is to open using the contextual menu, I can't repro. So anyways, I can use this test case to import/test the fix.

**Comment by rezad1393** [comment] 2015-11-02 20:34
I have this issue.

**Comment by hfa2010** [comment] 2015-11-05 02:43
I also have this issue while using tt-rss hosted locally.

**Comment by rezad1393** [comment] 2015-11-06 00:46
to be exact , umatrix sets the scope to the last requested address from the tab. if it is a new address click for example by  click on a link that is opened in a new tab then the umatrix in first tab sets it scope to the scope of the address opened in the second tab.
click a new address in the first tab first set the scope to that and so on.
this doesnt happens if you use middle click for opening in new tab.

this become really obvious when using things like web rss readers like inoreader.

**Comment by Diazonium** [comment] 2015-11-07 14:24
I can reproduce this issue, with the jsfiddle link, but not with the monoprice one.

**Comment by vzjrz** [comment] 2015-11-07 14:33
@Diazonium yeah sorry about that they seemed to have changed the site I can't reproduce either.

**Comment by zazdxscf** [comment] 2015-11-10 13:10
I might be having the same issue. For me, it happens when I do (right click on the tab and the select the) `Move to New Window`, for example while watching a youtube video. It seems to be working okay (in the new window) but then trying to add that video to a (youtube) playlist or even sharing it(clicking Share) gets stuck and it seems to be because of this:
![umuntitled](https://cloud.githubusercontent.com/assets/13550712/11062891/08b3bf58-87b3-11e5-9f13-5ea09b713d29.png)
![ubuntitled](https://cloud.githubusercontent.com/assets/13550712/11062892/0b829a38-87b3-11e5-8fdf-d849a68b5233.png)


Both uBlock and uMatrix are detecting the currently open site(the one in the New Window) wrongly, so everything(new) is thus denied, which explains stuff not working anymore.

uMatrix 96ffb97a34a7550a912bfa2339cfd94403718b23
uBlock 5cac23dfd7def3cd44c80080692b18b8953d31b9

Firefox 42.0 https://gist.github.com/zazdxscf/51ea4c46e7fd0e2391c8

Hopefully you won't need my uMatrix config to reproduce...

**Comment by TempSpas** [comment] 2015-11-12 18:59
I can reproduce this pretty reliably on Firefox 42.0. I have Reddit as a pinned tab, and any time I click on a link that takes me to a different site in a new tab, returning to the pinned tab will replace the scope with that of the site I just opened.

**Comment by gorhill** [comment] 2015-11-15 14:58
Dev notes.

This is the pain we have to deal with on Firefox -- using above easy-to-repro case. Open the `jsfiddle.net` page in a tab (step 1), then when clicking the embedded link, step 2. and beyond occur:

1. `TabContext.update: tabId=4 rawURL="https://jsfiddle.net/vu4fvn8w/embedded/result/"`
1. `TabContext.update: tabId=6 rawURL="about:blank"`
1. `TabContext.update: tabId=4 rawURL="http://www.google.com/"`
1. `TabContext.update: tabId=4 rawURL="http://www.google.ca/?gfe_rd=cr&ei=c5tIVvWKA8uh8wedup3YBg"`
1. `TabContext.update: tabId=4 rawURL="https://www.google.ca/?gfe_rd=cr&ei=c5tIVvWKA8uh8wedup3YBg&gws_rd=ssl"`
1. `TabContext.update: tabId=6 rawURL="https://www.google.ca/?gfe_rd=cr&ei=c5tIVvWKA8uh8wedup3YBg&gws_rd=ssl"`
1. `TabContext.update: tabId=4 rawURL="https://jsfiddle.net/vu4fvn8w/embedded/result/"`

As expected, Firefox will open a new tab (`tabid === 6`). But unexpectedly, it will open the link destination (`google.com`) in the current tab as can be seen in step 3. Eventually the destination link will be bound to the proper tab (step 6.), but the damage is done to the current tab.

**Comment by CrisBRM** [comment] 2015-11-15 16:21
Wait, so this was caused by a firefox update? I don't remember having this issue before

**Comment by luxoflux** [comment] 2015-11-24 11:58
[**@gorhill**](https://github.com/gorhill) commented on [Oct 25, 2015, 3:10 AM PDT](https://github.com/gorhill/uMatrix/issues/395#issuecomment-150910635 "2015-10-25T10:10:58Z - Replied by Github Comment Enhancer"):
> A similar issue was fixed with uBO ([issue 248](https://github.com/gorhill/uBlock/issues/248)), but this one I could reproduce. Being able to reproduce the problem here is important as this would allow me to import the fix from uBO, and to confirm it works.

This was not fixed for uBO. I can still reproduce (1.3.6rc0).

**Comment by skibbipl** [comment] 2015-11-24 12:19
I'm not observing this bug anymore with latest dev uMatrix build.

**Comment by gorhill** [comment] 2015-11-24 12:39
> This was not fixed for uBO. I can still reproduce (1.3.6rc0).

I am unable to reproduce with uBO. What are your steps to reproduce?

**Comment by luxoflux** [comment] 2015-11-24 12:45
[Steps](https://github.com/gorhill/uBlock/issues/248#issuecomment-106426095) to reproduce have not changed. But I am now using https://jsfiddle.net/vu4fvn8w/embedded/result.

**Comment by gorhill** [comment] 2015-11-24 12:48
Ok, that's the one I just tried and it works fine from here.

**Comment by luxoflux** [comment] 2015-11-24 12:52
Well, I really can't think of why this very specific issue would affect only me.

**Comment by gorhill** [comment] 2015-12-05 18:21
@luxoflux What version of Firefox is used to reproduce the issue on your side?

**Comment by luxoflux** [comment] 2015-12-11 11:50
This issue has finally disappeared for me. I totally cleared my uBO profile and just imported my rules manually and I haven't been able to reproduce it since. Weird.

**Comment by gorhill** [comment] 2015-12-11 15:16
@luxoflux I think this [new block of code](https://github.com/gorhill/uBlock/commit/4fd71d4209d46f4efbec47e2d372605e177b8c17?diff=unified#diff-8334c71c60f201b518259aad4d0bddd8R2118) has put a nail in the coffin of that bug: it was added to improve popup blocking reliability, but it also addresses all issues where uBO was given the wrong tab id for when a new web page is opened. I brought that fix to uMatrix once I found it worked well for uBO.

**Comment by luxoflux** [comment] 2015-12-12 00:38
That had to have been it, because I just updated to that version yesterday. Thank you.

**Comment by AlphaDelta** [comment] 2016-01-30 01:23
This appears to still be affecting Pale Moon (I'm running 26.0.0 x64, uMatrix 0.9.3.2).

<img src="https://i.imgur.com/cSAnZxa.png" />

**Comment by gorhill** [comment] 2016-01-30 04:34
Can't reproduce with Pale Moon 25.8.1 (x64) -- so it appears this could be specific to 26.0. Can you try to reproduce on your side with 25.8.1?

**Comment by AlphaDelta** [comment] 2016-01-30 05:52
I managed to reproduce it on Pale Moon 25.8.1 (x64), however I then disabled all other extensions and then *failed* to reproduce it. I tested to see which combination of extensions was causing this and it seems a combination of uBlock and uMatrix is causing this issue.

**Comment by aoaaxy** [comment] 2016-02-10 15:23
Using the steps from [above](https://github.com/gorhill/uMatrix/issues/395#issuecomment-177041460) and performing the google search for "test" and clicking the wiki link for "Test", the **scope is correct** for me(eg. en.wikipedia.org). 
 However google.com cookies/requests appear there. (see pic1)
 Refreshing the page (click or shift+click, or uMatrix's reload button) doesn't change anything in the matrix, and a cleared uMatrix log will show all those requests (eg. to read google's cookies) are being executed again with each refresh. (see pic2) [this might be important]
 Opening a new tab however and pasting the current link ( https://en.wikipedia.org/wiki/Test ) will show the expected matrix. (see pic3)

Can also reproduce this by google searching for eg. "Wired-Marker" then visiting the search result leading to https://addons.mozilla.org/en-US/firefox/addon/wired-marker/ You'll see google.com cookies and www.google.com requests in uMatrix while you're on that page. (the scope is still correct however)

Firefox 44.0 (dev.ed.)on gentoo linux
uMatrix commit: 3150395375acf28ab6644469ba98f6945f3e2db6
uBlock Origin commit: 98b0967d69a6d1403268b4514155e25ca8b33115
NoScript 2.9.0.3
https-everywhere commit: 7095f5a7af10c68076227c848e8b0d08796bd94c

**pic1:**
![cookies1](https://cloud.githubusercontent.com/assets/17016209/12951198/7050e57c-d011-11e5-927f-9c98e33ec5e5.png)


**pic2:**
![cookiepic2](https://cloud.githubusercontent.com/assets/17016209/12951224/8d64e7a8-d011-11e5-8d9b-8f67501b0d32.png)

**pic3:**
![cookies2](https://cloud.githubusercontent.com/assets/17016209/12951229/91d2d296-d011-11e5-9704-ba50dbf12795.png)

**Comment by JaneSmith** [comment] 2016-08-16 22:09
I think I'm experiencing this bug on Ubuntu 16.04 with Firefox 48.0. It can be easily reproduced: simply open a web page in the browser, then drag that tab out into a new window. uMatrix will then display the scope as "blank.about-scheme", with no connections listed at all. The only other scope in the drop-down menu is the global scope. Refreshing the page corrects this.

**Comment by gorhill** [comment] 2016-08-16 23:01
> open a web page in the browser, then drag that tab out into a new window

Unrelated to the issue here. This is same as https://github.com/gorhill/uBlock/issues/1120.

**Closed** 2017-11-13 19:53 UTC
Labels: unable to reproduce
