### ISSUE TITLE
chrome extension resize bug

### ISSUE THREAD

**Issue by gcb** [gorhill/uMatrix#790] opened 2017-05-24 18:24 UTC
I've used uMatrix for a long time on firefox (linux) without any problem. Just installed now on chrome  (osx) and some sites the extension open for a brief instant, and then collapse on itself. I can't scroll with mouse wheel or any other way.

I can reproduce it 100% of the time on pandora _after_ i enable media for that site.

tested with the version on the chrome extension store(sic) and with the latest pre-release from here.

![screen shot 2017-05-24 at 11 19 29](https://cloud.githubusercontent.com/assets/56283/26419102/6fb8b5bc-4073-11e7-9baf-0db8c7eb595f.png)

**Comment by gorhill** [comment] 2017-05-24 19:57
Duplicate of #694.

**Closed by gorhill** 2017-05-24 19:57 UTC
