### ISSUE TITLE
matrix cells not drawn (white matrix shown)

### ISSUE THREAD

**Issue by falzonec** [gorhill/uMatrix#728] opened 2017-03-14 18:19 UTC
On Chrome 57.0.2987.98 I have been hitting a bug where occasionally the matrix is not drawn properly and the column headers and domain scopes appear out of place. See [this screenshot](http://imgur.com/a/I0BL3).

By escaping/closing the matrix and opening it will likely be redrawn.

**Comment by gorhill** [comment] 2017-03-14 19:05
Duplicate of #711.

**Closed by gorhill** 2017-03-14 19:05 UTC
