### ISSUE TITLE
Safari Extension

### ISSUE THREAD

**Issue by AlexPoulsen** [gorhill/uMatrix#676] opened 2016-12-03 02:37 UTC
I used to use HTTP switchboard on Chrome; Now I use Safari (because of distrust for google).
Are there any technical limitations preventing this from being a Safari Extension too?

**Comment by gorhill** [comment] 2016-12-03 05:16
Duplicate of #96.

**Closed by gorhill** 2016-12-03 05:16 UTC

**Comment by will1818** [comment] 2016-12-13 00:12
@AlexPoulsen please also see https://github.com/drduh/macOS-Security-and-Privacy-Guide/issues/93 for safari issues, you are better off sticking with chromium

**Comment by AlexPoulsen** [comment] 2016-12-13 00:44
I will look into deleting those automatically, thanks. I would consider using chromium, but never chrome.
