### ISSUE TITLE
Why are my cookies deleted?

### ISSUE THREAD

**Issue by gitgetgot** [gorhill/uMatrix#508] opened 2016-02-27 21:15 UTC
Hi, forgive me, if asking the obvious, but...

I've read the introduction-text here: https://github.com/gorhill/uMatrix/wiki/Cookies
as well as the dashboard texts here:
![screenclip](https://cloud.githubusercontent.com/assets/974980/13375403/ae3feb5e-dd9e-11e5-8f3f-e49442c67d00.png)

but I still don't understand, why uMatrix still deletes cookies from sites that I have open tabs. (It also deleted the GitHub cookie while I was here typing ...)

![screenclip](https://cloud.githubusercontent.com/assets/974980/13375417/fe22e07c-dd9e-11e5-8f4f-56fd9dd3f4d4.png)
![screenclip](https://cloud.githubusercontent.com/assets/974980/13375419/06813b1a-dd9f-11e5-90bf-e906cbfb3492.png)

The upper screenshot also shows my settings, so you can see, no cookie option is activated.

I don't want my cookies to be deleted.

Is this by design, if so, why?

Thank you :)

(Firefox 43.4 win7, 64Bit)

**Comment by gorhill** [comment] 2016-02-27 21:26
Will close after one day if no precise steps are provided to reproduce the filed issue.

**Comment by gorhill** [comment] 2016-02-27 21:33
Did you turn off cookie deletion _after_ visiting the sites for which you say the cookies were deleted?

**Comment by gorhill** [comment] 2016-02-27 21:41
Never mind, I see 

    cookie deleted: http://thetvdb.com/{session-cookie:PHPSESSID}

In the logger turning off cookie deletion and then visiting `http://thetvdb.com/`.

Investigating.

**Comment by gorhill** [comment] 2016-02-27 21:50
Duplicate of #489.

**Closed** 2016-02-27 21:51 UTC

**Comment by gitgetgot** [comment] 2016-02-27 22:20
Thanks, 
just for information, I use other addons which deal with cookies:

Self-Destructing Cookies 0.4.9
and 
Cookie Manager Button
and
I don't care about cookies

**Comment by gorhill** [comment] 2016-02-28 13:30
My mistake, it's a duplicate of #385, not #489.
