### ISSUE TITLE
[Request] Have old xpi version of uMatrix for new realese to use with Pale moon and Firefox esr

### ISSUE THREAD

**Issue by macronit** [gorhill/uMatrix#901] opened 2017-12-30 17:49 UTC
[Request] Have old xpi version of uMatrix for new release to use with Pale Moon and Firefox esr.
With :  webext.xpi is not possible.

**Comment by gorhill** [comment] 2017-12-30 17:59
Duplicate of #824.

**Closed by gorhill** 2017-12-30 17:59 UTC
