### ISSUE TITLE
0.9.0.0: Matrix with new collapsed domain lines confusing

### ISSUE THREAD

**Issue by ghost** [gorhill/uMatrix#190] opened 2015-05-12 18:19 UTC
I think you introduced the new collapsed domain lines with the prefixed asterisk in the 0.9.0.0-rc?. I'm affraid that it will be a bit confusing for many users. See this example:

The matrix with the collpased github.com line indicates that there is a request for `other`:

![collapse1](https://cloud.githubusercontent.com/assets/1099173/7594744/0d73c1c8-f8e3-11e4-89a2-2318dc5a9b30.png)

Once unfolded (which is, btw, nowhere documented) we see that live.github.com is affected (surprisingly only in Firefox but not in Chrome ...):

![collapse2](https://cloud.githubusercontent.com/assets/1099173/7594745/0d7cba12-f8e3-11e4-813e-2eca6442de39.png)

Now, if we allow `other` for live.github.com and collapse the github.com.com line again it still shows a blocked request for `other` which is incorrect:

![collapse3](https://cloud.githubusercontent.com/assets/1099173/7594903/0ee751a4-f8e4-11e4-8cd6-82f67f5dd741.png)

**Comment by tlu1024** [comment] 2015-05-12 18:26
Aside from this probelm I think there are two otehr ones.
1. That littel triangle is hard to detect.
2. Many users will not understand why github.com is collpased and api.github.com is visible but live.github.com is hidden. I guess that's confusing.

**Comment by gorhill** [comment] 2015-05-12 18:26
I didn't change anything. I suspect it's a regression bug from implementing a better incremental rendering (to avoid rebuilding the whole DOM counterpart of the matrix).

Rows with explicit rules are not supposed to collapse into the meta `*.` row, so the last picture shows a bug. Will look into this.

**Comment by gorhill** [comment] 2015-05-12 18:33
I just tried your last scenario, and my `live.github.com` row does not collapse, it stays visible.

Re.:

> btw, nowhere documented

My dream is that one day there will be less pointing out what is not documented, and more just taking care of documenting it instead.

**Comment by gorhill** [comment] 2015-05-12 18:35
This is what I get:

![c](https://cloud.githubusercontent.com/assets/585534/7595292/1c0aa442-f8b4-11e4-8dc7-da9a307f2088.png)

So I don't know how to reproduce you case.

**Comment by gorhill** [comment] 2015-05-12 19:05
> new collapsed domain lines

Now I realize that you think the collapsing is new... Really? This has been in HTTPSB since November 2013: https://github.com/gorhill/httpswitchboard/issues/55#issuecomment-29132745.

**Comment by gorhill** [comment] 2015-05-12 19:30
Looking at the code, I failed to see how your last picture:

![a](https://cloud.githubusercontent.com/assets/1099173/7594903/0ee751a4-f8e4-11e4-8cd6-82f67f5dd741.png)

could happen, **unless** the rule you just set, `other` for `live.github.com`, was removed. Your eraser is dimmed, suggesting that whether:

1. You saved that new rule, but then it should not collapse out of view.
2. You erased that new rule, and it should collapse out of view (as in your pic)

As said, it's code that exists since Nov. 2013, and I never saw it failing, and the [code itself is rather unambiguous](https://github.com/gorhill/uMatrix/blob/c8f162d0bb48470d5cf4a8714ef81083e66c2113/src/js/popup.js#L392): rows which have cells with explicit rules are not collapsible.

I will wait for exact step to reproduce.

**Comment by tlu1024** [comment] 2015-05-12 20:08
I tried again, and I couldn't reproduce, either. 

Regarding those collapsed lines in HTTPSB: Hm, now that you're mentioning it I remember. However, up to 0.8.1.3  I think I haven't really noticed it. Is it possible that the unfolded status was the default then?

But perhaps this is another example (among others) that I'm getting senile. Thus, my collaboration makes less and less sense. I'm ringing down the curtain on it. 

Thanks a lot for your great extensions and all the best for you.

**Comment by gorhill** [comment] 2015-05-12 23:03
>  I'm ringing down the curtain on it.

Well that really sucks, you were one of the most early adopters.

**Comment by gorhill** [comment] 2015-05-14 13:43
Ok I confirm that the rows were now collapsed by default, which was not the case before. The collapse/expand state is now saved locally as a UI preferences (so that it appears in `about:config` in FF). From this change, I did not take into account that the initial state could be undefined, and this caused rows to be collapsed by default. This has been fixed in 6369d37567bc00e2763c03acd67c25aff867b6cb.

**Closed by gorhill** 2015-05-14 13:43 UTC
Labels: unable to reproduce
