### ISSUE TITLE
Startpage search results not displayed unless uMatrix javascript enabled.

### ISSUE THREAD

**Issue by PassinThrough2** [gorhill/uMatrix#260] opened 2015-06-09 02:58 UTC
Firefox version: 39.01
uMatrix versions: 0.9.1.2 and 0.9.1.3
uMatrix settings: 1st party images and CSS enabled, default deny rest
Site: https://startpage.com/

I believe this is due to some change Startpage made Sunday, and it is currently being discussed here: https://www.reddit.com/r/privacy/comments/38zuwz/startpage_now_requires_javascript_to_show_results/

When I enter any search into startpage, just the upper portion of the results page is displayed, no results are shown. Enabling javascript in uMatrix corrects, but a Startpage representative claims javascript is not needed. I did disable javascript in about:config on a fresh occurrence of Firefox, and Startpage search results were indeed shown.

**Comment by luxoflux** [comment] 2015-06-09 04:42
This appears to be related to how uMatrix/uBlock handles `<noscript>` tags (https://github.com/gorhill/uBlock/issues/308). Startpage sets `#page-wrapper { visibility: visible }` in `<noscript>` when javascript is disabled. If <noscript> isn't handled properly it remains set to `visibility: hidden`. No such issue with NoScript.

Current options are to use Stylish and set `#page-wrapper` to always visible or use https://classic.startpage.com.

**Comment by gorhill** [comment] 2015-06-09 11:31
On the other hand, letting `noscript` tags work was causing Google Search page to be blank with Firefox (#232)...

**Comment by d-kr** [comment] 2015-06-09 14:50
Well, on twitter links (t.co) it has the opposite effect. For example: https://t.co/8mTCHSo3uQ (If there is no javascript enabled, then that page is blank because neither `<meta ...`inside `<noscript>` nor `<script ...` will be executed. ( view-source:http://t.co/8mTCHSo3uQ )

**Comment by luxoflux** [comment] 2015-06-09 18:28
I personally think the user should be alerted to "meta redirections" with temporary/permanent options to allow or deny—that would take care of _that_ problem. The other issues with `<noscript>` are up for discussion (@gorhill, could you go over them here so we can all come up to speed?).

**Comment by gorhill** [comment] 2017-12-02 22:58
Duplicate of #319.

Fixed in next release.

**Closed by gorhill** 2017-12-02 22:58 UTC
Labels: duplicate
