### ISSUE TITLE
umatrix scroll issue on firefox

### ISSUE THREAD

**Issue by Coverlin** [gorhill/uMatrix#857] opened 2017-11-29 00:32 UTC
![giphy 1](https://user-images.githubusercontent.com/34079190/33351498-bde6c9e0-d4ac-11e7-9121-23d95837ad22.gif)

Scrolling to the end of the list and then highlighting an element with the mouse would reset the scroll to top

**Comment by gorhill** [comment] 2017-11-29 12:15
Duplicate of #784.

Next time please be more considerate when you file an issue: provide **all** the relevant details. Browser/version is always key. Also, _always_ search the issue tracker before opening a new issue: <https://github.com/gorhill/uMatrix/issues?q=is%3Aissue+scroll+is%3Aclosed>.

**Closed by gorhill** 2017-11-29 12:15 UTC
Labels: duplicate
