### ISSUE TITLE
Extension UI not reacting to clicks [unresponsive?] (since Chrome / Chromium 57)

### ISSUE THREAD

**Issue by pauschu** [gorhill/uMatrix#729] opened 2017-03-15 17:12 UTC
I am a happy user of uMatrix. Since Chrome version 57 (at least I didn't notice before) there is a bug that the extension's UI is (sometimes) unresponsive. But after closing and opening the UI multiple times it becomes responsive again. [Watch here for clarification](https://www.comff.net/umatrix_bug_unresponsive_chrome_57.gif)

Some more points to mention:

- I really clicked everytime the cursor is above the "all" field in the video
- Clicking on any other field also does not work
- I am experiencing this issue on Windows and Linux (didn't test Mac so far)
- The issue can happen on any website (couldn't find a reasonable scheme behind it)
- Even with fresh Chrome/Chromium profile and with installing ONLY uMatrix the issue still appears
- It happens only in (maybe) 10-20% of all the uses. But it happens often enough to annoy me so far that I created this Github issue here.

**Comment by gorhill** [comment] 2017-03-15 17:35
Any error at the extension's dev console?

**Comment by gorhill** [comment] 2017-03-15 17:48
Never mind, I just reproduced. I can confirm this is duplicate of #711.

**Comment by pauschu** [comment] 2017-03-15 17:49
popup.js:259 Uncaught TypeError: Cannot read property 'temporary' of undefined
    at getTemporaryColor (popup.js:259)
    at getCellAction (popup.js:405)
    at handleFilter (popup.js:430)
    at handleBlacklistFilter (popup.js:443)
    at HTMLDivElement.<anonymous> (popup.js:1347)

**Closed by gorhill** 2017-03-15 17:48 UTC

**Comment by pauschu** [comment] 2017-03-15 17:50
And sorry for creating a duplicate I just filtered by the "bug" label and there was nothing so I just created it.
