### ISSUE TITLE
CSP error notification -> Conflicting with uBlock Origin?

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [gorhill/uMatrix#967] opened 2018-03-13 20:27 UTC
Switched from an Amazon page where I blocked almost nothing with uMatrix to a new tab and loaded a site that blocked everything except the frame and CSS. Suddenly I get a notification on Chrome telling me I've got an "extension error" or something, and when I reviewed my extensions, the following warning appeared:
>Warning:
>This extension failed to modify the response header "Content-Security-Policy" of a network request because the modification conflicted with another extension (uBlock Origin).
![screenshot_20180313_205811](https://user-images.githubusercontent.com/1091166/37366636-47bf003c-2701-11e8-8d05-f39f6a5d166f.png)

No idea if that is a bad thing, both uBlock Origin and uMatrix seem to continue to work as expected.

Settings
![screenshot_20180313_205917](https://user-images.githubusercontent.com/1091166/37366680-696d3fc8-2701-11e8-83a3-1bc906a95dd8.png)
![screenshot_20180313_205943](https://user-images.githubusercontent.com/1091166/37366703-799cef24-2701-11e8-8b5a-58ca495a5192.png)
![screenshot_20180313_212356](https://user-images.githubusercontent.com/1091166/37367852-db31590c-2704-11e8-8224-c34b26b6c5ed.png)
![screenshot_20180313_212418](https://user-images.githubusercontent.com/1091166/37367869-e6ecc632-2704-11e8-87f5-c4ac5a0c77a5.png)
![screenshot_20180313_212442](https://user-images.githubusercontent.com/1091166/37367896-f4b5ba9e-2704-11e8-99c4-483b6c7a0b0b.png)

- OS/version: Debian 9
- Browser/version: Chromium 64.0.3282.119
- uBlock Origin version: 1.15.2
- uMatrix: 1.3.2

**Comment by gorhill** [comment] 2018-03-13 20:29
Duplicate of #1170.

**Comment by gorhill** [comment] 2018-03-13 21:01
I decided to test an idea, and it worked, so re-opening -- I will need to experiment more to be sure though in case there was a flaw in my test.

This seems fixable if I inject a _new_ CSP header instead of modifying an existing one -- which both uMatrix and uBO do. This is probably a solution because it's allowed for servers to send [more than one CSP header](https://www.w3.org/TR/CSP3/#csp-header).

**Comment by uBlock-user** [comment] 2018-03-14 05:52
@gorhill Will this finally fix all other "extension errors" invoked via CSP or only this one in particular ?

**Comment by gorhill** [comment] 2018-03-14 12:22
Unfortunately, added response headers were not merged on Firefox 58 and less:
<https://bugzilla.mozilla.org/show_bug.cgi?id=1377689>, so this means the fix here is a regression for FF58 and less.

**Comment by uBlock-user** [comment] 2018-03-14 13:15
Will it work on Chromium ?

**Closed** 2018-03-24 21:20 UTC

**Comment by Okamoi** [comment] 2018-04-08 15:36
> This seems fixable if I inject a new CSP header instead of modifying an existing one -- which both uMatrix and uBO do. Speculating: this is probably a solution because it's allowed for servers to send more than one CSP header.

> Unfortunately, added response headers were not merged on Firefox 58 and less:
https://bugzilla.mozilla.org/show_bug.cgi?id=1377689, so this means the fix here is a regression for FF58 and less.

@gorhill I'm not sure how to conclude out of this, could you confirm or correct the following ?

Firefox 59 merges headers with the same name, which includes CSP headers, when there is more than one modified by an add-on.

Can a website infer from the headers that I have both uMatrix and uBO installed ? I'd rather have them only able to infer I have uBO, as it has many users. uMatrix is more of an oddball unfortunately and I'd rather not stand out if possible.

To reformulate the question, what can the website figure out from headers if I have both uBO and uMatrix installed ?

Thanks!
