### ISSUE TITLE
Problem dark theme firefox

### ISSUE THREAD

**Issue by Bundy01** [gorhill/uMatrix#834] opened 2017-11-23 22:28 UTC
Hello,

I have a dark theme on linux. So I enabled the system colors in the "preferences" of firefox. The problem is that I don't have the colors in Umatrix or UblockO. The problem was already present on firefox 56 and now on Quantum.

screenshot: [url](https://s8.postimg.org/er2xuitl1/Capture_du_2017-11-15_19-33-20.png)

**Comment by gorhill** [comment] 2017-11-23 22:30
Try the beta build on AMO, this was fixed: <https://github.com/gorhill/uMatrix/pull/804>.

**Comment by Bundy01** [comment] 2017-11-23 22:44
Sorry but with version 1.1.11b0, I have the same problem

**Comment by gorhill** [comment] 2017-11-23 23:24
Ok, I hadn't looked at your picture because it was a 404 -- I now fixed your image URL.

You are talking about the matrix panel. The issue is quite certainly on your side, you will have to investigate yourself. It seems to me your are using user styles in your Firefox, and these override uMatrix styles. It's for you to fix on your side.

**Closed** 2017-11-24 02:55 UTC
Labels: external
