### ISSUE TITLE
feature request: popup which shows the filenames

### ISSUE THREAD

**Issue by Ulf3000** [gorhill/uMatrix#625] opened 2016-09-21 20:38 UTC
is it jquery.js or badasstrojan.js  :D  ?  a little popup could solve that question very swiftly. 

it would be nice to have a  popup (over a cell in the panel ) which shows the filenames of the requested files.

opening the logger and searching through the list takes a long time, so blocking or not becomes a question of trial and error. 

i request this feature because a similar addon which im still using "policeman" has this feature and its easy to see which ressources are tried to load by the tab! it makes policeman very smooth and easy to use  . i think its policemens most outstanding feature.

so i would welcome that feature in u matrix of course XD 
 
thanx for listening

**Comment by gorhill** [comment] 2016-09-21 20:50
Duplicate of #78.

**Closed by gorhill** 2016-09-21 20:50 UTC
