### ISSUE TITLE
Feature request: add "Go anyway" to "uMatrix has prevented the following page from loading" page

### ISSUE THREAD

**Issue by qwertier** [gorhill/uMatrix#628] opened 2016-09-23 16:46 UTC
It's a frequent case when preventing page from opening feature is useful. But, sometimes I want to go to the page even knowing the site is suspecting... 
So, "Go anyway" would be very helpful to users. Now, I have to use "enable/disable" uMatrix button in the addon popup which is not very handy!

**Comment by gorhill** [comment] 2016-09-23 18:04
Duplicate of #203.

**Closed by gorhill** 2016-09-23 18:04 UTC
