### ISSUE TITLE
uMatrix pop-over window not displaying properly.

### ISSUE THREAD

**Issue by ericdand** [gorhill/uMatrix#767] opened 2017-04-20 18:20 UTC
Possibly related to #683. 

Often on websites, I go to open uMatrix and it only shows the bottom-left two-thirds of the window. Here is a screenshot: 

<img width="514" alt="screen shot 2017-04-20 at 10 30 26 am" src="https://cloud.githubusercontent.com/assets/2456006/25245929/f077ad76-25ba-11e7-8f7a-7090156bef84.png">

I am unable to scroll up or right to the cropped content (though I can still scroll down when there is a lot of stuff to be shown). 

Also possibly relevant:

https://bugs.chromium.org/p/chromium/issues/detail?id=428044

The last comment (Mar 24 2017) on that issue suggests setting the extension's display setting to "none" until it's done loading, then changing it to something like "block" in a callback.

This happens to me on all kinds of websites, about 50% of the time I open the uMatrix window. Sometimes closing and reopening the window a couple of times fixes it; sometimes it seems entirely stuck like this.

**Comment by gorhill** [comment] 2017-04-20 18:25
Browser version?

**Comment by ericdand** [comment] 2017-04-20 18:29
@gorhill Whoops, of course. I'm using Chrome version 58.0.3029.81 (64-bit), on a MacBook (from 2015, with the Retina display).

**Comment by mustaqimM** [comment] 2017-04-25 10:17
@gorhill I'm having the same problem on Nightly 55.0a1 with the `webext` v1.0.0. I am unable to scroll down and sometimes the popup doesn't open and the twice, the icon was hidden.

**Comment by gorhill** [comment] 2017-04-25 13:36
Duplicate of #694 -- specific to OSX.

**Closed by gorhill** 2017-04-25 13:36 UTC
Labels: duplicate
