### ISSUE TITLE
Unblockable media/other items in Firefox

### ISSUE THREAD

**Issue by hotdogman** [gorhill/uMatrix#381] opened 2015-10-17 16:27 UTC
uMatrix 0.9.2.3
Firefox 41.0.2

Tested with default uMatrix settings & clean Firefox profile.
1. Clear cache
2. Navigate to http://kara.8ch.net/b/
3. Notice that there is loud/annoying auto-playing audio in the background
4. Remove

```
* * css allow
* * frame block
* * image allow
* 1st-party * allow
* 1st-party frame allow
```

so that only  
`* * * block` is left.
5. Open the logger
6. Refresh the page
6. Notice that there is still auto-playing audio in the background, despite the fact that the logger reports everything blocked

Note: It appears Firefox isn't reporting any media/audio in the [Network Monitor](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor) either.

**Comment by gorhill** [comment] 2015-10-17 16:59
Duplicate of #199.

**Comment by hotdogman** [comment] 2015-10-17 17:26
This may be a duplicate, so I apologize if it is, but with #199, the logger still reports the request as 'doc'.
Both the logger, and the network monitor, don't report any network requests.

**Comment by hotdogman** [comment] 2015-10-17 18:04
This may be a duplicate of #199, so I apologize if it is, but with #199, the network monitor still reports a request.
![xmztz7-kdev_ 1](https://cloud.githubusercontent.com/assets/4343306/10560340/6e9bb016-74ce-11e5-8595-77e59c53b5ec.png)
The network monitor isn't reporting any requests for the audio/media files here, though, but they're still playing in the background.
![o70qaujvajxp 1](https://cloud.githubusercontent.com/assets/4343306/10560384/88bc17c8-74cf-11e5-8656-c9759d9c763f.png)

**Comment by gorhill** [comment] 2015-10-17 19:21
Could be related to this: <https://github.com/chrisaljoudi/uBlock/issues/955>.

**Comment by gorhill** [comment] 2017-12-02 23:16
Since this is about Firefox legacy, closing -- I no longer maintain a version for Firefox legacy.

**Closed by gorhill** 2017-12-02 23:16 UTC
Labels: wontfix
