### ISSUE TITLE
Sync support for settings and rules of umatrix.

### ISSUE THREAD

**Issue by skudo12** [gorhill/uMatrix#66] opened 2014-11-22 04:37 UTC
I noticed that umatrix settings and ublock settings doesn't support syncing. 
I tried with one computer, installed umatrix and ublock. Then tried in the other computer, it only downloads umatrix and ublock but the settings is not intact.

**Comment by ctcherry** [comment] 2015-01-27 18:49
If possible I would really like this as feature well!

**Comment by busybeaver** [comment] 2015-02-06 18:45
The feature would really simplify the usage of uMatrix on multiple devices (in my case 3)...

**Comment by d-kr** [comment] 2015-02-06 19:02
Is it possible to encrypt (or hash) the filter or host names? Because ...ehm ... lets say I'm not "proud" of some of my rules.

**Comment by acidicX** [comment] 2015-05-14 17:53
I would love to have this on Firefox as well!

**Comment by tYYGH** [comment] 2015-05-20 08:15
I'd be interested as well.
I'm curently using "RequestPolicy Sync", but since RequestPolicy is not an option anymore on Firefox 38, I'm going to switch to whichever extension is going to support FF sync first: either RequestPolicyContinued, or uMatrix…

**Comment by acidicX** [comment] 2015-05-20 08:24
imho RequestPolicyContinued works quite well (I don't know if it support syncing out of the box though?), but uMatrix has a nicer interface and allows finer control...

**Comment by ivelichko** [comment] 2015-05-25 22:12
It would be really greate to have this sync feature.

**Comment by ttsda** [comment] 2015-05-31 12:20
I think this feature is essential for anyone who uses more than a single computer daily.

**Comment by griels** [comment] 2015-07-07 12:43
+1.

**Comment by eFiggy** [comment] 2015-07-28 01:00
Yes, a sync feature would be wonderful! I'm on different computers all the time and it would be nice to not have to keep white/blacklisting items I've already configured elsewhere. Thanks for this great extension!

**Comment by lkraav** [comment] 2015-07-28 05:10
This would also be great from a company management perspective, where a set of computers could get the base rules from a central repository, and always stay up to date.

**Comment by mailinglists35** [comment] 2015-08-05 17:09
+1

**Comment by gorhill** [comment] 2015-08-05 17:13
> to synchronize some text files

Settings are saved into storage provided by the browser, through a browser API. Extensions are not allowed to create file on a user's file system (for good reasons).

**Comment by mailinglists35** [comment] 2015-08-05 19:37
> Extensions are not allowed to create files on a user's file system (for good reasons).

@gorhill but if we take those files out and overwrite copy them to a working umatrix storage folder, will it work? or are they uniquely sticked to a particular browser profile directory?

**Comment by adrienbeau** [comment] 2015-08-05 21:22
Firefox stores extension data in a binary SQLite database file. For example under Linux: `$HOME/.mozilla/firefox/xxxxxxxx.default/extension-data/umatrix.sqlite`

Chrome also stores extension data in a binary SQLite database file. For example under Windows:
`%LOCALAPPDATA%\Google\Chrome\User Data\Xxxxxxx\Local Storage\chrome-extension_ogfcmafjalglgifnmanfmnieipoejdcf_0.localstorage` (there is also a matching `.localstorage-journal` file).

I'm not sure you can copy the binary files between different operating systems, architectures and browsers. If you use exactly the same software (OS and browser) on both sides, it could work, provided the two browsers are turned off when you copy the file.

Maybe you could use SQLite database tools to dump the data from one side, and inject it in the other side.

**Comment by mailinglists35** [comment] 2015-09-13 19:23
@gorhill what if we create github accounts for example, can you add saving/loading settings to/from it as external storage? (github is just an example; we could have ftp, dropbox, etc). you are already providing export/import to/from file. what would be the easiest *online* storage support for you?

obviously this is not really a high priority for your project but more a side task but it would really be useful to end-users managing multiple installations.

**Comment by gorhill** [comment] 2015-09-13 19:31
The latest [dev build](https://github.com/gorhill/uMatrix/releases) support Chromium/Firefox sync for rules.

**Comment by mailinglists35** [comment] 2015-09-26 15:10
thanks, but how do I sync across browsers? I'm using it in firefox, chrome, opera... :(

**Comment by tYYGH** [comment] 2015-09-28 09:28
@gorhill Thank your for providing the dev build.
I've been using it for a week on one Firefox, and it worked perfectly, including pushing to my Sync server, I suppose (no visible error).

However, this week-end, I tried installing it on another Firefox, and I could not find how to retrieve the cloud-stored rules… After cloud is enabled, I see the new button to push the rules to the Sync server, but there is no button to retrieve the rules *from* the server; I suppose this button would appear after having pushed the rules *to* the server at least once, but then my previously-sync'ed rules would get overwritten!
What did I do wrong?

**Comment by gorhill** [comment] 2015-09-28 12:53
> but then my previously-sync'ed rules would get overwritten!

It's a Firefox caveats, spelled out in the [doc](https://github.com/gorhill/uBlock/wiki/Cloud-storage#firefox-browsers):

> A new installation of uBlock Origin will cause cloud storage data to be blanked.

Bugzilla: <https://bugzilla.mozilla.org/show_bug.cgi?id=753289>. Apparently fixed in latest Nightly, I did not try for myself the fix.

**Comment by tYYGH** [comment] 2015-09-28 13:49
I see. So let's assume that I copy my rules to a text file, and manually set the rules to those in this text file each time I install uMatrix on a new Firefox, and upload again the (same) rules in order to bootstrap the sync process on each new Firefox profile.
Will the rules thereafter actually sync between the different Firefox'es, even though the UI only shows the "up" button at first, and not the "down" button?

**Comment by gorhill** [comment] 2015-09-28 13:52
I would expect the "import" button to become available as soon as uMatrix sees there is data in the cloud (sorry for buzzword). Currently it's not showing in your case because the new uMatrix install zero-ed the cloud storage, and so uMatrix sees nothing available for download.

**Comment by tYYGH** [comment] 2015-09-29 10:44
@gorhill: I did as I said, and I got the result you said :-)
As far as I'm concerned, the issue is solved for Firefox, even though automatic sync would be a nice option (hint :-p )
Thank you gorhill for this excellent release!

**Closed** 2015-09-29 12:17 UTC
