### ISSUE TITLE
How can I completely disable JavaScript on page? 

### ISSUE THREAD

**Issue by mtomas7** [gorhill/uMatrix#541] opened 2016-04-07 19:23 UTC
Hello,

when I was using NoScript on Firefox, and was testing my website, it would trigger no-script warning message that webusers would see if JS is blocked, but with uMatrix set to block everything this warning still is not triggered. That means JS is still executed.

Is there a way to block all JS by default? I want to have similar settings as in NoScript blocking all.

Thank you!

**Comment by gorhill** [comment] 2016-04-07 19:32
> That means JS is still executed.

No, it means `noscript` tags are not parsed. See <https://github.com/gorhill/uMatrix/issues/319>.

Closing as duplicate of #319.

**Closed by gorhill** 2016-04-07 19:32 UTC
