### ISSUE TITLE
One minor uMatrix setting is deleted with cookies

### ISSUE THREAD

**Issue by Okamoi** [gorhill/uMatrix#863] opened 2017-12-02 17:21 UTC
Hi,

uMatrix on Firefox has one tiny preference that gets wiped when people clear cookies, the `I want to hide all blacklisted domains from the drop down menu` setting. By default domains blacklisted by filter lists or personal rules are displayed, but a simple click collapses them all into a single line.

Unfortunately, uMatrix forgets this setting when cookies are deleted. You can reproduce the loss of this setting with the CTRL+SHIFT+DEL interface where literally everything is selected. If instead you don't select cookies _and_ offline data, then the preference will not be forgotten by uMatrix.

Would you mind sharing which API you use to store data that isn't deleted with the CTRL+SHIFT+DEL interface, while we are at it ? The developer of the Tree Tabs add-on would really benefit from knowing this, all his settings get deleted the way I described, and there can be quite a lot.

Thanks!

uMatrix 1.1.12
Firefox 57
Windows 7 64-bit

**Comment by gorhill** [comment] 2017-12-02 17:32
Duplicate of #852. Fixed in current dev build.

> Would you mind sharing which API you use to store data that isn't deleted with the CTRL+SHIFT+DEL interface

I don't know what is "CTRL+SHIFT+DEL interface".

uMatrix saves its persistent settings (those parts of a backup file) through browser.storage.local.

IndexedDB is used to save the content of the remote hosts files.

There is also window.localStorage used to persist small convenient UI settings. This is what was used to save the collpasing of the blacklisted hostnames section. That setting has now been converted as a persistent setting.

**Closed by gorhill** 2017-12-02 17:32 UTC
Labels: duplicate

**Comment by Okamoi** [comment] 2017-12-02 17:42
Thanks, so I'll suggest him `browser.storage.local` or IndexedDB instead of anything tied to the `window` object.

> Duplicate of #852. Fixed in current dev build.

Ah crap, sorry I did not notice it.

> I don't know what is "CTRL+SHIFT+DEL interface".

I don't know how to access it without a shortcut these days. This one:

https://s18.postimg.org/jlhkcjl5l/delete.jpg

**Comment by Thorin-Oakenpants** [comment] 2017-12-03 00:57
> I don't know what is "CTRL+SHIFT+DEL interface".

gorhill, in FF that is the "Clear All/Recent History" dialog which allows removal of various items such as cookies, various histories, **Offline Website Data** etc .. it is this item I bold'ed that causes the issue
![clearalldialog](https://user-images.githubusercontent.com/16656956/33521169-69c8e2c2-d82f-11e7-8019-b2bff1bde490.png)

### uBo issue <sup>may be related</sup>

Apologies if this is the wrong place to bring this up, but it seems relevant to a weird issue - I think this is the same issue that @grauenwolfe was experiencing (Mac, FF57, latest uBo stable a week or so ago) where the collapsed state of the 3rd party lists in the dashboard becomes `stuck` - see https://github.com/ghacksuserjs/ghacks-user.js/issues/273#issuecomment-346779584 (or I will summarize below)

Dashboard set like this (collapsed)
![](https://user-images.githubusercontent.com/25858089/33202097-bee2995e-d0c0-11e7-9d44-2ee101e30630.png)
Clear **Offline Website Data** via various methods such as Clear All History and collapsible state is reset

The problem is that the setting is no longer and can cause a collapsed state to stick
> For example, if I collapse a filter group it will stay collapsed indefinitely until OWD is cleared

Could this setting's storage location be moved? Or is this a non event and nothing needs to be done? I couldn't replicate on Windows.

**Comment by gorhill** [comment] 2017-12-03 04:53
> The problem is that the setting is no longer and can cause a collapsed state to to stick

I don't see how it's possible. uBO tests the stored value with `=== 'y'`, I don't see how this could ever succeed if the storage was cleared, the returned value in such case is `undefined`.

I just tried, and when I clear "Offline Website Data", uBO's `window.localStorage` is cleared and the UI in your screenshot is reset.
