### ISSUE TITLE
Cannot import whitelist from NoScript

### ISSUE THREAD

**Issue by c-mart** [gorhill/uMatrix#552] opened 2016-05-20 17:31 UTC
From #270 and [release 0.9.2.0](https://github.com/gorhill/uMatrix/releases/tag/0.9.2.0):

> Can import whitelist directives from NoScript export file. These will translate into `* [hostname] script allow` rules.

I couldn't get this import to work, running NoScript 2.9.0.11 on Firefox and uMatrix 0.9.3.3 on Chromium. I tried exporting from NoScript two different ways:

- Just the whitelist (Export button in the Whitelist tab of NoScript options)
- The entire settings dump (Export button at the bottom of the NoScript options window)

I tried importing each of the resulting files to uMatrix two different ways:
- "Import from file..." in the "My Rules" tab
- "Restore from file..." in the About tab

All four of these permutations failed silently. I have hundreds of NoScript whitelist rules and and am not (yet) a JavaScript developer, so I made this workaround to use until the issue is resolved. If it turns out this feature actually works and I was just doing it wrong, I'll be happy to document the correct procedure on a wiki page for this repo.

### Workaround: migrating NoScript whitelist to uMatrix
1. Export your rules from NoScript. Use the Export button in the Whitelist tab, not the overall settings Export button at the bottom of the window. This should produce a file with one hostname on each line.
2. Copy only the section of bare hostnames out of this file, as a block - I don't think you need to include the fully qualified URLs below them. *Be careful not to include the `[UNTRUSTED]` line and everything below it*, if you have this! That would be bad.
3. Paste your hostnames into the upper "Text" section of this RegExr, replacing the four example hosts: http://regexr.com/3df9j (Note that RegExr requires JavaScript to work)
4. Copy the resulting uMatrix rules out of the lower "Replace" section on that page.
5. Paste the new rules into uMatrix ("My Rules" tab -> Edit button), then click Save, then Commit.

(Also note that my Regex replace string creates `[hostname] 1st-party script allow` rules, which is more restrictive than `* [hostname] script allow `, e.g. Facebook's JS will only run while you're actually on facebook.com. Tweak this to suit your preferences.)

Also, I'm unsure who created the rules editor in the "My rules" tab, but it is a wonderful UI for managing differences between the permanent and temporary rulesets.

**Comment by coffeemakr** [comment] 2016-06-14 13:01
uMatrix expects the entire settings dump as the input file.
I think this issue is caused by a file type check. Try saving the file as `something.txt` and it should work fine.
What filename did you use?
Regards

**Comment by gorhill** [comment] 2016-06-24 12:42
Fixed with #572.

**Closed by gorhill** 2016-06-24 12:42 UTC
