### ISSUE TITLE
umatrix frame does not fully display

### ISSUE THREAD

**Issue by cybershambles** [gorhill/uMatrix#703] opened 2017-01-30 01:36 UTC
![image](https://cloud.githubusercontent.com/assets/7995198/22410169/8be12e84-e6e8-11e6-9421-d1720db8a6b2.png)
I need to click the button 2-10 times for the full content to be shown..

MacOS, Version 55.0.2883.95 (64-bit). Appstore umatrix.

**Comment by gorhill** [comment] 2017-01-30 05:25
Duplicate of #694.

**Closed by gorhill** 2017-01-30 05:25 UTC
