### ISSUE TITLE
[Question, Firefox] Are uMatrix settings synced with Firefox Sync?

### ISSUE THREAD

**Issue by castor-troy** [gorhill/uMatrix#236] opened 2015-05-29 04:59 UTC
It's not an issue, but a question. I don't know where else to post to get answers about uMatrix.
I am using Firefox developer edition.

1. Are uMatrix settings synced with Firefox Sync? Including the rules?
2. If I Install uMatrix manually from github releases, will they be automatically updated to the next pre-release or full-release?

**Comment by Snapy** [comment] 2015-05-29 10:25
@castor-troy The short answer is no but when it will be implemented it will be cross-platform.

**Comment by gorhill** [comment] 2015-05-29 12:29
Duplicate of #66.

**Closed by gorhill** 2015-05-29 12:29 UTC
