### ISSUE TITLE
missing icons on uMatrix and uBlock

### ISSUE THREAD

**Issue by share3141** [gorhill/uMatrix#960] opened 2018-02-24 20:21 UTC
I have a dual boot machine - Windows and Mint 18.3. I use Firefox on both - same release FF59b12. I use umatrix (1.3.2) and uBO (1.15.10) on both. On Windows for those two extensions I can see all the icons along the top. On Linux I can just some of the icons. For example, on uBO the blue icon is not present in Linux unless I change the setting.  I have narrowed the issue down to an entry in the config file.  "browser.display.use_document_fonts" - default value 0.  I changed the value to 1 and the problem disappeared.  Like I said - doesn't happen in Windows.

**Comment by share3141** [comment] 2018-02-24 20:26
There we go...here is an image.  Had to turn off UBO and uMatrix to get the file loaded!




![1](https://user-images.githubusercontent.com/20307002/36634729-dcc88662-19a0-11e8-82f1-f5d4baf19f4e.jpg)

**Comment by share3141** [comment] 2018-02-24 20:39
Maybe a little better example...
![2](https://user-images.githubusercontent.com/20307002/36634838-d7781202-19a2-11e8-9155-b5b652603eaf.png)

**Comment by share3141** [comment] 2018-02-24 20:44
Maybe a little better example...
![2](https://user-images.githubusercontent.com/20307002/36634881-77715494-19a3-11e8-864c-90d210fcc8c0.png)

**Comment by gorhill** [comment] 2018-02-24 20:48
Duplicate of <https://github.com/gorhill/uBlock/issues/2878>.

**Closed by gorhill** 2018-02-24 20:48 UTC
Labels: duplicate
