### ISSUE TITLE
uMatrix icon gone after last firefox update

### ISSUE THREAD

**Issue by MarcSN311** [gorhill/uMatrix#760] opened 2017-04-11 22:16 UTC
On Firefox Nightly Build 55.0a1 (2017-04-11) (64-bit) the uMatrix Icon disappeared from the Toolbar. (uMatrix version 1.12.0) it also doesn't appear in the customize screen, so it can't be manually added.

I tried this in a clean profile.

**Comment by gorhill** [comment] 2017-04-11 23:04
There is no version 1.12.0, that does not exist.

**Comment by MarcSN311** [comment] 2017-04-11 23:15
sorry i clicked on the wrong button, thats my uBlock Origin Version. uMatrix Version is 0.9.3.6

**Comment by gorhill** [comment] 2017-04-12 03:13
Duplicate of #756.

Please search existing issues before opening a new one.

**Closed by gorhill** 2017-04-12 03:13 UTC
Labels: duplicate

**Comment by MarcSN311** [comment] 2017-04-12 09:13
sorry, only searched for open issues.
