### ISSUE TITLE
Popup is not filled

### ISSUE THREAD

**Issue by UsernameIsAlreadyTaken12345** [gorhill/uMatrix#870] opened 2017-12-04 21:14 UTC
It seems that since the update to 1.1.14 the popup isn't filled correctly.
I had a similar problem with another addon and there I recognized 3 settings (about:config), that causes the problem. These settings causes also a problem with uMatrix:
dom.indexedDB.enabled=false
dom.storage.enabled=false
network.cookie.cookieBehavior=2
I've changed them for privacy reasons.

It's working again, when I change them to:
dom.indexedDB.enabled=true
dom.storage.enabled=true
network.cookie.cookieBehavior=1

Is it possible to make uMatrix working with the settings mentioned first?

**Comment by zippit** [comment] 2017-12-04 21:47
I have the same problem with update 1.1.14.  My settings are like the second list shown above with only one difference.  The first two entries are both set at true.  

The final entry is like the last entry in the first list at network.cookie.cookieBehavior=2

That is the entry that disables cookies.   When I change it to 1, the uMatrix extension shows the entries in the popup. 

It was working fine before the update.  This is happening on 2 different PCs.

**Comment by gorhill** [comment] 2017-12-04 21:52
Yes, a fix will be published shortly. Duplicate of #840.

**Closed by gorhill** 2017-12-04 21:52 UTC
Labels: duplicate

**Comment by gorhill** [comment] 2017-12-04 21:58
1.1.16 has been pushed to AMO, shouldn't take long before it's available.

Sorry about the issue.

**Comment by zippit** [comment] 2017-12-04 22:25
No problem.  This is a great extension!.
