### ISSUE TITLE
Blocked cookies are created by redirected requests (an.yandex.ru)

### ISSUE THREAD

**Issue by slimboored** [gorhill/uMatrix#726] opened 2017-03-09 19:14 UTC
How to reproduce: create rules, go to http://www.rbc.ru and click any news item, watch umatrix log & any cookie manager to analyze (built in is enough)

It seems like uMatrix shows that it blocked cookie in log, but the cookie was actually created & set, which is clearly shown in Cookie Manager and later this was confirmed by showing in uMatrix log that it was auto deleted (with Self Destructing Cookies i set 30 seconds to auto-delete)

http://i90.fastpic.ru/big/2017/0309/b1/fe86b819ef566328460282a4f1d4f2b1.png

uMatrix rules:
yandex.ru 1st-party cookie block
yandex.ru 1st-party frame block
yandex.ru 1st-party other block
yandex.ru 1st-party plugin block
yandex.ru 1st-party script block
yandex.ru 1st-party xhr block

uBlock dynamic rule to unlock Easyprivacy list:
no-strict-blocking: an.yandex.ru true

Found this very accidentally.. bug or feature?

**Comment by gorhill** [comment] 2017-03-09 20:21
Duplicate of #686.

**Closed by gorhill** 2017-03-09 20:21 UTC
Labels: duplicate, invalid
