### ISSUE TITLE
uMatrix sometimes detects the currently loaded website incorrectly

### ISSUE THREAD

**Issue by Diazonium** [gorhill/uMatrix#410] opened 2015-11-07 14:09 UTC
So I have been having some problems with websites breaking randomly for some time, but I have not been able to pinpoint the cause. But now I have caught something nasty:
![umatrix_bug](https://cloud.githubusercontent.com/assets/6989626/11015480/b5aa3a48-8560-11e5-9db9-c824d4512cf4.png)
As you can see, I am squarely on facebook.com, yet uMatrix thinks I am on hardverapro.hu, and tries to apply the rules belonging to that site, and that of course completely breaks Facebook.
I have to idea why this happened, but I think this cold be a major cause of random site breakage.

BTW, I am on Win 7 x64, Firefox 43.0 beta 1

**Comment by gorhill** [comment] 2015-11-07 14:12
Duplicate of #395?

**Comment by Diazonium** [comment] 2015-11-07 14:22
Possibly yes, but this is just a random event that I managed to capture, so I do not know exactly what I have done to trigger it. So at the moment I cannot give instructions to reproduce, but I will keep an eye out for similar events and post an update when I can reproduce.

**Comment by 5t3f4n** [comment] 2015-11-17 15:06
@Diazonium it's actually not random at all, and it's very easy to reproduce reliably.

* Be in [this very thread](https://github.com/gorhill/uMatrix/issues/410)
* Left-click on [the image](https://cloud.githubusercontent.com/assets/6989626/11015480/b5aa3a48-8560-11e5-9db9-c824d4512cf4.png) you included in the first post
 * It will open in a new tab
* The scope for the thread has changed from `github.com` to `cloud.githubusercontent.com`
* Things like previewing posts is now broken until you reload/navigate away from the site*

\* Assuming you don't allow scripts/xhr etc. from anywhere

I definitely think your issue is related to the one gorhill linked, and you probably encountered it by clicking on a link in the news feed or something.

**Comment by bmikosdi** [comment] 2015-12-22 06:50
Facebook.com: everytime, Firefox 64bit

**Comment by gorhill** [comment] 2015-12-22 12:34
Try dev build, it's supposed to be fixed.

**Closed** 2017-11-13 19:26 UTC
Labels: invalid
