### ISSUE TITLE
Grey UI glitch over some domain names.

### ISSUE THREAD

**Issue by pwd-github** [gorhill/uMatrix#846] opened 2017-11-25 14:00 UTC
This doesn't happen with all domain names. I've seen it on occasion and have been incredibly lazy, but since I was filing another bug today, I thought I should file this too. A quick check and I've got it to happen over bugzilla.mozilla.org and core77.com

1: Go to bugzilla.mozilla.org
2: Click the uMatrix icon
3: See 
![umatrixuiglitch](https://user-images.githubusercontent.com/203217/33231185-e52b9d30-d1e8-11e7-9265-5ad5b1770d21.png)

**Comment by gorhill** [comment] 2017-11-25 14:31
Please, read the release notes: <https://github.com/gorhill/uMatrix/releases/tag/1.1.8>.

It's by design. I had been smarter when I released the first version of uMatrix, this would have been the way I would have designed the scope selector.

**Comment by gorhill** [comment] 2017-11-25 14:32
Duplicate of #840.

**Closed by gorhill** 2017-11-25 14:31 UTC
