### ISSUE TITLE
Option to proceed to a link even if it's blocked?

### ISSUE THREAD

**Issue by 420pitts** [gorhill/uMatrix#305] opened 2015-07-26 19:12 UTC
uMatrix blocks links when it gets redirected from an ad network. An example would be in Yahoo Finance, clicking article links are blocked.

http://i.imgur.com/T5lNAcX.png

Can you make an option to proceed through this?

**Comment by gorhill** [comment] 2015-07-26 20:11
Duplicate of #203.

**Closed by gorhill** 2015-07-26 20:11 UTC
