### ISSUE TITLE
hostnames count doesn't update when updated the HOST file lists

### ISSUE THREAD

**Issue by uBlock-user** [gorhill/uMatrix#954] opened 2018-02-14 14:43 UTC
**STR**

1) Open dashboard > Assets

2) Take a note of hostname count for `Dan Pollocks host file` which is `13,272 used out of 13,278` on my end, could be different on yours.

3) Click on `clock` icon to remove the cache

4) Click on `Update Now` button, once the update finishes the count remains the same i.e. `13,272 used out of 13,278` even though the list was updated 2 days ago, so either the count should go lower(if entries were removed) or go up(if new entries were added), instead no change is shown in the count.

uMatrix -  1.3.3.8 
Chromium 66

**Comment by uBlock-user** [comment] 2018-02-14 14:45
@gorhill same issue with custom hosts lists too.

**Comment by gorhill** [comment] 2018-02-14 15:13
I don't see anything wrong. If I have only this one list enabled, the version shipped with uMatrix says "13,242 used out of 13,248". Forcing an update of the list results in the count becoming "13,272 used out of 13,278". Clicking the clock icon marks the list as out of date -- it does not remove the cache. Forcing an update of course will just cause the same version as the cached one to be downloaded, hence the count won't change.

**Comment by uBlock-user** [comment] 2018-02-14 15:18
So why does it happen with the custom file list of mine ? 

https://raw.githubusercontent.com/uBlock-user/uMatrix-Hosts-List/master/hosts.txt

Before update the total number is 24,149

I added a new entry called 0.0.0.0 analytics.github.com

I forced update it remains the same as 24,149.

Then I remove the custom list and add it back - the number changes to 24,150.

This didn't happen before. When I click Update not, it would fetch the newest version and the number would change i.e. become 24,150

**Comment by gorhill** [comment] 2018-02-14 15:21
Did you verify that the list is not pulled from the browser cache?

**Comment by uBlock-user** [comment] 2018-02-14 15:24
How do I verify that for this issue specifically ?

If I click on, listing it opens `chrome-extension://eckgcipdkhcfghnmincccnhpdmnbefki/asset-viewer.html?url=https://raw.githubusercontent.com/uBlock-user/uMatrix-Hosts-List/master/hosts.txt`

whichs shows the updated version, but the number count won't go up.

**Comment by uBlock-user** [comment] 2018-02-14 15:32
Added another entry 0.0.0.0 analytics.screenrant.com to my listing.

Clicked on `Purge All Caches` and still no effect. The number remains the same even though the count should have gone up to 24,151 from 24,150. I suppose this is a cache issue.

**Comment by uBlock-user** [comment] 2018-02-14 15:37
The only way it updates for me is if I remove the list and add it back.

**Comment by gorhill** [comment] 2018-02-14 15:42
> How do I verify that for this issue specifically ?

`chrome://extensions/` => "Developer mode" enabled => uMatrix => Click `background.html` => Select _Network_ pane => Force an update of the list => see if request if fetched from cache:

![a](https://user-images.githubusercontent.com/585534/36213050-a8485f0a-1173-11e8-97bd-5f0afeec629e.png)

**Comment by gorhill** [comment] 2018-02-14 15:45
> Clicked on `Purge All Caches` and still no effect. The number remains the same even though the count should have gone up to 24,151 from 24,150.

Purging the cache just cause the list to be marked as obsolete, it does not remove it from the cache.

**Comment by uBlock-user** [comment] 2018-02-14 15:48
There you go - 

![](https://i.gyazo.com/75ccb9812b0594513ac37910ff042f81.png)

It fetched 145 KB, so it's not from cache, and the number still remains the same. 

I found this too in the console - 

![](https://i.gyazo.com/5f8096c9003a74f1cc2696c38f9a2178.png)

**Comment by uBlock-user** [comment] 2018-02-14 16:06
Funny thing is, this doesn't happen with uBlock Origin, I mark it out of date and then click on Update now and it gets updated successfully.

**Comment by uBlock-user** [comment] 2018-03-05 04:43
The issue is still going on, the number won't update after marking out of date and clicking on Update Now. This didn't happen before.

But if I deactivate, click Apply Changes and then activate and click Apply Changes again, the number updates.

**Comment by gorhill** [comment] 2018-03-05 11:08
I explained [above](https://github.com/gorhill/uMatrix/issues/954#issuecomment-365647732) to you why this is this way.

**Comment by uBlock-user** [comment] 2018-03-05 12:18
I'm asking for a solution, how do I deal with this ?

**Comment by gorhill** [comment] 2018-03-05 12:36
A solution to what? There is no issue = nothing to solve. Having uMatrix fall back to the packaged version is not a desirable behavior. And even then, there is no guarantee that the number of hostnames in the packaged version will be different then the current one. You focus unduly about a number, what matters is whether the list is marked as obsolete or not.

**Comment by uBlock-user** [comment] 2018-03-05 12:38
> You focus unduly about a number

So how do I know that the list has been updated or not ? That number is the only way to know.

**Comment by gorhill** [comment] 2018-03-05 13:00
> So how do I know that the list has been updated or not ? That number is the only way to know.

Really? Guess which one is up to date and which is not not up to date.

![a](https://user-images.githubusercontent.com/585534/36976100-5b56220a-204a-11e8-84a8-b69d7eb65612.png)

If you still do not trust, use the logger to see the network request being made. If you still do not trust all the evidences, the burden is on you to make the case there is an issue, not on me to convince you there is none -- I spent already way too much time on this non-issue.

**Comment by uBlock-user** [comment] 2018-03-05 13:08
If that's the acceptable way then why is it different with uBlock Origin ? Why isn't the behavior same there ?

**Comment by gorhill** [comment] 2018-03-05 13:25
There is no difference with uBO.

**Comment by uBlock-user** [comment] 2018-03-05 13:38
The number updates after the update is complete.

**Comment by gorhill** [comment] 2018-03-05 13:44
I did update and the number didn't change after the update was completed.

**Comment by uBlock-user** [comment] 2018-03-05 13:48
On my end, it did.

Resource Abuse

Before update -

![](https://i.gyazo.com/d8c50eae52059ea64c474b8eb2c3f0b1.png)

After update

![](https://i.gyazo.com/2f13d5d284b07634d794344ec97ef905.png)

**Comment by gorhill** [comment] 2018-03-05 13:51
So? You provide no details as to when was the last update for that resource.

Now try again:

- Click the clock icon: number does not change
- Click "Update now" and let it complete: number does not change

**Comment by uBlock-user** [comment] 2018-03-05 13:53
> So?

So I made my point, the number changes when I force update the list on uBO, since you said "There is no difference with uBO." That's the difference.

> You provide no details as to when was the last update for that resource.

Few days ago, week perhaps, I don't exactly keep a date in mind.

**Comment by uBlock-user** [comment] 2018-03-05 13:54
> Now try again:

Obviously it wouldn't change now, because I just updated it to show it to you.

**Comment by uBlock-user** [comment] 2018-03-05 13:56
But in case of uMatrix, I updated the filter list today and there was no change, the last update I made was also a week ago. Do you get my point now ? If not, I rest my case. I can't be more crystal clear anymore.

**Comment by gorhill** [comment] 2018-03-05 14:26
> Do you get my point now ?

No. Note that only you is seeing an issue here. Feel free to find other people who can side with you and maybe explain in other words what I supposedly fail to understand.

**Comment by uBlock-user** [comment] 2018-03-05 14:41
> Feel free to find other people who can side with you 

Why would I want anyone to "side" with me ? If people want to support on their own then it's fine. I don't anyone to fight the case for me. I reported it because I'm facing a difficulty in ascertaining whether uMatrix was able to update the list or was it still pulling from the cache, and from the appearance it's still pulling the cache and since I'm the only one appear to having this issue, I will let it go.

**Comment by nameless3** [comment] 2018-03-05 15:59
In Firefox 59.0b13, uMatrix 1.3.3b8, I just updated Peter Lowe's list (old list from March 3th, new from March 5th) and the counter stays the same (it's still 1,753 used out of 2,583​​ despite the new list having 2,608 entries).

Unchecking the list -> apply changes -> check list -> apply changes again, and now the counter is updated (1,786 used out of 2,608).

And updating lists in uBlock, the counter indeed changes right away without having to uncheck lists (and has done so as long as I remember).

**Comment by gorhill** [comment] 2018-03-05 16:37
I think I am reproducing it now -- investigating.

**Comment by gorhill** [comment] 2018-03-05 16:46
@uBlock-user You were right, I was wrong, sorry for wasting your time.

**Closed** 2018-03-05 16:47 UTC

**Comment by uBlock-user** [comment] 2018-03-05 16:50
I'm just glad this finally got your attention. Thanks to @nameless3 for taking his time and posting his findings.

**Comment by uBlock-user** [comment] 2018-03-05 16:54
Was this a regression after implementing selfies in uMatrix ?

**Comment by gorhill** [comment] 2018-03-05 17:02
Yes. I forgot how much stuff changed in the current beta -- I have been mostly working on uBO lately. I am not yet setup to publish a self-hosted signed version of uMatrix beta -- so for now I will have to push an unsigned version with the fix.

**Comment by uBlock-user** [comment] 2018-03-07 15:15
@gorhill A vertical white space-line appears near the scroll bar in popup UI since 1.3.3.9

STR

Browse - https://www.washingtonpost.com/news/the-fix/wp/2018/03/07/the-7-most-interesting-parts-of-stormy-danielss-lawsuit-against-trump/

Open the popup UI

Notice the vertical white-space line near the scrollbar like this - 

![](https://i.gyazo.com/5eedd19e066950a92f668a3b542c59f1.png)

**Comment by gorhill** [comment] 2018-03-07 15:26
There has been no change in that area in 1.3.3b9 relative to 1.3.3b8: <https://github.com/gorhill/uMatrix/compare/1.3.3b8...1.3.3b9>.

**Comment by uBlock-user** [comment] 2018-03-07 15:41
I haven't seen it before 1.3.3.9, can you take a look ? It only happens on websites where there are lots of connections made which causes the scrollbar to appear in the popup UI along with the vertical white space.

**Comment by gorhill** [comment] 2018-03-07 16:31
I can not reproduce with Chromium 64.

I can reproduce with Chrome 66 (dev build).

So it looks like a regression in the dev build of the browser.

**Comment by uBlock-user** [comment] 2018-05-25 11:52
I can still reproduce it on Chromium 68, I don't think it's a regression anymore, it would have been fixed by now.

**Comment by uBlock-user** [comment] 2018-09-18 04:11
> I can still reproduce it on Chromium 68, I don't think it's a regression anymore, it would have been fixed by now.

Doesn't happen in Chrome 71 appears to be been fixed, reproducible on 69 though, so it was a regression after all.
