### ISSUE TITLE
Allow to control non http connections as well

### ISSUE THREAD

**Issue by SmoothDude** [gorhill/uMatrix#542] opened 2016-04-08 21:31 UTC
Looking through src/js/traffic.js file at line 101 one can see that non http connections can go through and it does give sites oportunity to insert contents (and bugs) using non http protocols (like ftp) without possibillity to control them through uMatrix

**Comment by lewisje** [comment] 2016-04-09 05:04
I'm thinking that the problem is that the browser APIs that uMatrix relies on only intercept HTTP(S) connections, and this is known to be a serious issue with WebSocket (WS) connections in uBlock: https://github.com/gorhill/uBlock/issues/1497

**Comment by Atavic** [comment] 2016-09-15 20:07
non-http schemes are handled in the browser options or at system level.
http://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

**Comment by Atavic** [comment] 2017-12-04 19:28
[websockets-security-overview](https://gist.github.com/AglaianWoman/f7ee8fa17fe570203b0bab21919e313e#websockets---security-overview)

**Comment by gorhill** [comment] 2017-12-10 22:39
uMatrix/webext uses `<all_urls>` now in the manifest, so I will close this.

**Closed by gorhill** 2017-12-10 22:39 UTC
Labels: unable to reproduce
