### ISSUE TITLE
[Chrome] uMatrix shall be accessible via keyboard/context menu

### ISSUE THREAD

**Issue by alekwo** [gorhill/uMatrix#690] opened 2017-01-04 14:47 UTC
Some popup windows do not have the toolbar with icons visible. In such windows, it's not possible to change permissions in uMatrix. I think there shall be an alternative way of accessing the uMatrix settings for a window - like a keyboard shortcut or having it in a right-click/context menu. 

![2017-01-04_1546](https://cloud.githubusercontent.com/assets/24917047/21646069/f8993e8a-d294-11e6-89b3-107e45ff97f1.png)

**Comment by Jendrik3** [comment] 2017-01-07 19:36
Same for firefox.

**Comment by gorhill** [comment] 2017-01-07 19:48
Duplicate of #287.

**Closed by gorhill** 2017-01-07 19:48 UTC
