### ISSUE TITLE
Firefox 53 + uMatrix 0.9.3.6 sometimes disappears the login and password menu on the sites. 

### ISSUE THREAD

**Issue by eldrik1** [gorhill/uMatrix#768] opened 2017-04-22 14:08 UTC
Sometimes disappears the login and password menu on the sites. If uMatrix disable this does not happen. On previous versions of the firefox this was not. 
<a href='https://hostingkartinok.com/show-image.php?id=8e7837abe9bbb8fca51a66eb754a7a67' title='хостинг фотографий'><img style="width:100%" src='https://s8.hostingkartinok.com/uploads/images/2017/04/8e7837abe9bbb8fca51a66eb754a7a67.png'  /></a>
<a href='https://hostingkartinok.com/show-image.php?id=996be22da9b38e162f142e55921e4a4e' title='хостинг скриншотов'><img style="width:100%" src='https://s8.hostingkartinok.com/uploads/images/2017/04/996be22da9b38e162f142e55921e4a4e.png'  /></a>

**Comment by gorhill** [comment] 2017-04-22 14:25
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2017-04-22 14:25 UTC

**Comment by Thorin-Oakenpants** [comment] 2017-04-26 11:03
FYI: I suspect the issue is to do with this: [Resource URI Leak add-on setting causes Firefox 53 login/password problems](https://github.com/ghacksuserjs/ghacks-user.js/issues/89) ... 

"No Resource URI Leak" FF add-on, options->"Block Web-exposed subset of chrome:// URIs" (and it has a warning) and is disabled by default.

So something to do with chrome:// blocking

**Comment by gorhill** [comment] 2017-04-26 11:45
To be clear, uMatrix/uBO do not expose `chrome://`/`resource://` URIs to web pages --  Resource URI Leak is not needed for these specifically.

**Comment by Thorin-Oakenpants** [comment] 2017-04-26 12:38
Sorry, I didn't mean to impl uMatrix or uBo were leaking resources, or that they were at fault. My message was meant for OP as a possible solution/clue - the link describes the exact same symptoms and it was traced back to "a subset of chrome://URIs", whatever that may actually be.

**Comment by gorhill** [comment] 2017-04-26 12:49
> Sorry, I didn't mean to imply uMatrix or uBo were leaking resources

Sure, it's just me wanting to be sure there is no misunderstanding for whoever reads this here -- since according to OP, disabling uMatrix fixed his issue (no case was made that uMatrix is doing something wrong, so the assumption is that the issue is with his ruleset).

**Comment by Thorin-Oakenpants** [comment] 2017-04-26 13:35
No worries - edited my first post to clarify in case someone doesn't read on :)
