### ISSUE TITLE
uMatrix claims a request is being made when it isn't.

### ISSUE THREAD

**Issue by Stebalien** [gorhill/uMatrix#469] opened 2016-01-23 01:42 UTC
When I load [the dmd manual](https://www.gnu.org/software/dmd/manual/dmd.html) the following gets logged (both the "dmd manual" log and the "All" log):

```
20:27:05			cookie	http://www.google.com/insights/consumersurveys{session-cookie:PAIDCONTENT}
20:27:05			cookie	http://www.google.com/{session-cookie:DV}
20:27:05			cookie	http://google.com/verify{session-cookie:SNID}
20:27:05			cookie	http://google.com/{session-cookie:OGP}
20:27:05			cookie	http://google.com/{session-cookie:NID}
20:27:05			cookie	http://google.com/{session-cookie:OGPC}
20:27:04			doc		https://www.gnu.org/software/dmd/manual/dmd.html
```

Furthermore, uMatrix claims that the page is trying to load a script from google.

However, the dmd manual is not making any requests to google, I see no requests to google in the network log, and I see no requests to google in wireshark (i.e. no one is talking to google).

(And yes, I stopped of uMatrix/uBlock when testing).

Platform: Firefox (linux)

**Comment by vzjrz** [comment] 2016-01-23 01:46
You don't have any other scripts or addons running because I'm not seeing this.

**Comment by Stebalien** [comment] 2016-01-23 01:55
I have a bunch of other addons running and, now that I've restarted Firefox, I'm not seeing this any more. However, something fishy is going on... I'll close this for now but hopefully someone else will run into it. I only noticed because I know that gnu would never include javascript from google.

**Comment by Stebalien** [comment] 2016-01-23 01:58
Scratch that. This happens on any page opened from a google link, even after reloading the page (all extensions except uMatrix disabled).

**Comment by gorhill** [comment] 2016-01-23 02:10
Duplicate of #221.

**Closed by gorhill** 2016-01-23 02:10 UTC

**Comment by Stebalien** [comment] 2016-01-23 02:17
Got it. Thanks!
