### ISSUE TITLE
[Firefox] Inline script blocked but not shown in the matrix

### ISSUE THREAD

**Issue by ghost** [gorhill/uMatrix#177] opened 2015-05-09 12:08 UTC
http://www.spiegel.de/video/mittelmeer-tausende-fluechtlinge-vor-libyen-gerettet-video-video-1574547.html

![spiegel](https://cloud.githubusercontent.com/assets/1099173/7550098/9c6097d0-f654-11e4-870f-442254794845.png)

Please note that I haven't installed the flashplugin.

**Comment by gorhill** [comment] 2015-05-09 16:11
Fixed in 486183cbe6d3256c554bbd85b84676089bcab4d2.

I had to remove the ability to move the popup around, this was causing way too many edge issues, and the amount of code to deal with these was no longer justified, especially it was probably still failing in more edge cases.

The popup is not pinned near the top-right corner, and I added a control button to minimize it to get it out of the way to see what is under.

**Comment by gorhill** [comment] 2015-05-09 16:43
I can't reproduce. It shows 6 scripts, 1 frame, 1 css. It does not report images however, despite the page being full of them. I suspect this is because they are cached. But I don't know if that would also explain the inline script count. What version of uMatrix?

**Comment by gorhill** [comment] 2015-05-09 16:45
Can you show me the log for that page, for when you get this result? Whatever the log sees, it should be reported in the matrix, it's the same code path.

**Comment by tlu1024** [comment] 2015-05-09 17:02
Here we go:

The following 3 screenshots represent the log if the site is loaded:

![spiegel2](https://cloud.githubusercontent.com/assets/1099173/7551140/b34caa64-f67d-11e4-8b57-eb0619d9a2d9.png)
![spiegel3](https://cloud.githubusercontent.com/assets/1099173/7551141/b37b4f86-f67d-11e4-80fc-a5669880c11a.png)
![spiegel4](https://cloud.githubusercontent.com/assets/1099173/7551142/b38c82ec-f67d-11e4-884f-7e01ceefd7da.png)

And once I click the play button in the video I get this:

![spiegel5](https://cloud.githubusercontent.com/assets/1099173/7551148/dd19077a-f67d-11e4-89e3-5419bf4d48f2.png)

**Comment by tlu1024** [comment] 2015-05-09 17:05
One general question: Do you know a trick how to make a screenshot of the matrix in Firefox? Other than in Chrome it vanishes too fast when I press the print key. (I'm not talking about the sticky matrix in the logger.)

**Comment by gorhill** [comment] 2015-05-09 17:11
Here is a simpler case: <https://news.ycombinator.com/news>.

No external script, only one inline script tag. What result do you get?

**Comment by gorhill** [comment] 2015-05-09 17:13
What version of uMatrix? You seem to have a lot of behind-the-scene requests.

**Comment by tlu1024** [comment] 2015-05-09 17:21
![ycombinator](https://cloud.githubusercontent.com/assets/1099173/7551209/8d56be50-f680-11e4-9d30-759aa5b1730a.png)

I'm using dev7.

**Comment by gorhill** [comment] 2015-05-09 17:35
So... what does the matrix says for that test?

Isn't the issue you filed about `script` cells showing empty?

**Comment by gorhill** [comment] 2015-05-09 17:45
Ok, let's step back here. Too many little disparate nuggets of information, raising more questions. Issues should detailed as thoroughly as possible in the **first** comment, this saves a lot of back and forth time.

Your comment, at the top:

1. No uMatrix version number.
    - The amount of behind-the-scene requests resemble what was happening with uMatrix `dev.0`. I can't get this kind of output. Now you say `dev.7`, but is it `dev.7` for the last test, or `dev.7` for the first test too?
2. No Firefox version.
3. The screenshot you provided in OP is truncated, I can't see the most important information, which is the entries immediately following the doc boundary for the link you provided.
4. Reading again, I am not even sure what the **exact** issue is. You gave me a URL, I loaded that URL and all work as expected, the matrix is filled with information.

I can't read mind, so can we start over and explain carefully what is the issue?

**Comment by tlu1024** [comment] 2015-05-09 18:12
> No uMatrix version number.
    The amount of behind-the-scene requests resemble what was happening with uMatrix dev.0. I can't get this kind of output. Now you say dev.7, but is it dev.7 for the last test, or dev.7 for the first test too?

For all tests dev7.

> No Firefox version.

37.0.2 64bit on Arch Linux

> The screenshot you provided in OP is truncated, I can't see the most important information, which is the entries immediately following the doc boundary for the link you provided.

Okay, here is the complete log for that site.

![sp](https://cloud.githubusercontent.com/assets/1099173/7551420/9a134d3c-f687-11e4-992d-9dcb4752a2e7.png)

![sp1](https://cloud.githubusercontent.com/assets/1099173/7551378/6b85e4d0-f686-11e4-908a-00b068578992.png)
![sp2](https://cloud.githubusercontent.com/assets/1099173/7551377/6b36a9b0-f686-11e4-926c-023bf011a928.png)

> Reading again, I am not even sure what the exact issue is. You gave me a URL, I loaded that URL and all work as expected, the matrix is filled with information.

As shown in the screenshot 
`http://video.spiegel.de/flash/74/54/1574547_1024x576_H264_HQ.mp4{inline_script}` is blocked according to the logger but there is no corresponding entry in the matrix.

> Transcribing the relevant rules/switches in use helps a lot too.

The rules for spiegel.de as shown in the screenshot. My settings:

![settings](https://cloud.githubusercontent.com/assets/1099173/7551409/477000de-f687-11e4-9b88-6d7559c285f5.png)

and all hosts files enabled.

**Comment by gorhill** [comment] 2015-05-09 18:39
How is your video playing? Mine won't play without Flash.

**Comment by gorhill** [comment] 2015-05-09 18:46
Please, paste here **all** your `spiegel.de` rules, **no screenshot**, I can't cut & paste screenshots in the Rules pane.

**Comment by gorhill** [comment] 2015-05-09 18:57
Unable to reproduce with the provided steps.

**Comment by gorhill** [comment] 2015-05-09 23:37
I've been refactoring script blocking stuff to be more inline with how it's done in uBlock. I don't know if that changes anything for the case in your first comment<sup>[1]</sup>, but might be worth a try.

[1] I have no clue how you end up with a `doc` for `http://video.spiegel.de/flash/74/54/1574547_1024x576_H264_HQ.mp4`.

**Comment by tlu1024** [comment] 2015-05-10 11:22
I apologize. These are my rules:

spiegel.de spiegel.de plugin allow
spiegel.de video.spiegel.de frame allow
spiegel.de www.spiegel.de frame allow
spiegel.de www.spiegel.de script allow
spiegel.de www.spiegel.de xhr allow

Now with dev9 there is a change indeed: The logger doesn't show a blocked inline script anymore.

![sp](https://cloud.githubusercontent.com/assets/1099173/7554048/081d0bee-f717-11e4-9364-e1b4c9ddc7a1.png)

> How is your video playing? Mine won't play without Flash.

Neither does mine:

![sp1](https://cloud.githubusercontent.com/assets/1099173/7554051/58a14e4a-f717-11e4-8930-b76e4d0838a2.png)

**Comment by gorhill** [comment] 2015-05-10 12:31
I don't get that dialog box. This explains everything. Your Firefox is trying to download the video, mine plays the video right in the page. My Flash is completely disabled, it's playing HTML5, with "JW" player.

**Comment by gorhill** [comment] 2015-05-10 12:35
So now looking at this, I think the problem to solve here is no longer script reporting stuff, but the fact that your matrix should not be changed by that download-video dialog box, as no new page is opened. uBlock deal properly with this, but I had to change thing in uMatrix as it works differently.

I will try to address this today.

**Comment by tlu1024** [comment] 2015-05-10 14:57
>  I don't get that dialog box. This explains everything.

Sorry for not mentioning this earlier. I failed to see that this is responsible for a script that is blocked in the logger but not reported in the matrix.

**Comment by gorhill** [comment] 2015-05-10 15:06
This is not an HTML document, this is an MP4 file. There is no script tag to report. The issue of uMatrix reporting blocked inline script in the logger was fixed with the refactoring. If a document has no inline script tag at all, no "{inline-script}" event will be reported in the logger. So this is fixed.

The issue to solve is not script-related: the matrix should not be set up for a downloaded file: a downloaded file should be seen as a secondary resource for the current tab, and the matrix of the current tab should be the one appearing in the popup.

**Comment by gorhill** [comment] 2015-05-10 15:29
I still would like to be able to reproduce by the way, as a test case for the matrix thing.

**Comment by tlu1024** [comment] 2015-05-10 15:37
Hm, what else can I provide?

**Comment by gorhill** [comment] 2015-05-10 15:39
The question is, why is your video not playing embedded in the page, I am pretty this is the intended behavior. It's what happens in my Firefox for that page.

**Comment by tlu1024** [comment] 2015-05-10 15:57
I have no idea. I tried it with uMatrix and uBlock0 disabled but with the same result. So it's definitely not related to something being blocked by those extensions.

**Comment by hotdogman** [comment] 2015-05-10 22:43
I believe that this is, while fixed in uMatrix, remains present in uBlock.
https://a.pomf.se/avonjf.webm

**Comment by SkySkimmer** [comment] 2015-05-11 22:39
@tlu1024 
>One general question: Do you know a trick how to make a screenshot of the matrix in Firefox? Other than in Chrome it vanishes too fast when I press the print key which starts ksnapshot in my case since I'm using KDE.
Use the snapshot delay (http://a.pomf.se/qvxyai.png in the red rectangle). Steps:
-hit print to get ksnapshot
-set delay to 1 or 2 seconds and take new snapshot
-before the delay ends open the matrix
-when the delay ends you will get a snapshot with the matrix open

**Comment by tlu1024** [comment] 2015-05-12 10:43
@SkySkimmer : Wow, this works really great! Such an easy solution - and I had not noticed it ...

Thanks a lot!

**Closed** 2017-12-02 16:07 UTC
Labels: unable to reproduce
