### ISSUE TITLE
Google search result page doesn't redirect to non js page

### ISSUE THREAD

**Issue by Daniyal-Javani** [gorhill/uMatrix#861] opened 2017-12-01 13:58 UTC
When I disable JS the google redirect me to a page that is not require JS for filters like filter time. But when I disable JS with uMatrix it doesn't redirect me to that page. Any idea of how to do that? I'm using Firefox on Ubuntu 16.04

**Comment by gorhill** [comment] 2017-12-01 14:15
Duplicate of #319.

**Closed by gorhill** 2017-12-01 14:15 UTC
Labels: duplicate
