### ISSUE TITLE
Not reading settings correctly?

### ISSUE THREAD

**Issue by alejandrolemus** [gorhill/uMatrix#168] opened 2015-05-07 23:55 UTC
I just installed uMatrix for Firefox, and despite me not marking delete cookies (blocked nor non-blocked), or spoof user-agent, the logger shows activity stating it's spoofing the ua-string and deleting all kinds of cookies.
So apparently uMatrix it is not reading those settings correctly?

Edit: images added

![dashb](https://cloud.githubusercontent.com/assets/9505902/7528269/7e32900e-f4f3-11e4-9c63-03821e7ce210.png)
![delcook](https://cloud.githubusercontent.com/assets/9505902/7528272/82cacdb6-f4f3-11e4-90e7-a45023b435bc.png)

**Comment by alejandrolemus** [comment] 2015-05-08 00:20
Also, from the translation strings, I assume you are dropping the µ character. If so, you missed the one showing in the dashboard. No big deal, just reporting.

**Comment by gorhill** [comment] 2015-05-08 00:21
For user agent, the string is rotated internally, but not necessarily used. Still I will log the operation only if it's really in use.

For cookies, I can't reproduce.

**Comment by gorhill** [comment] 2015-05-08 00:26
Actually, looking at the code I see what is happening, yes, it appears cookies can be deleted regardless of settings -- will fix.

**Comment by alejandrolemus** [comment] 2015-05-08 00:27
FWIW, it's Firefox 37.0.2 in Windows 7. I didn't check/uncheck those (at least I don't remember doing it), only ticked both <b>Convenience</b> options and updated the filterslist

**Comment by asymmetric** [comment] 2015-05-08 08:31
@gorhill : amazing work on the new FF addon. One thing: can we use a GH "firefox" label instead of having "Firefox" in the title?

**Comment by gorhill** [comment] 2015-05-08 10:52
@asymmetric I created labels for firefox, chromium. The issue here is core, so I removed "Firefox" from the title.

**Comment by gorhill** [comment] 2015-05-11 20:15
Actually, I retract my _"I will log the operation only if it's really in use"_. This is a per-scope switch, so although it can be disabled globally, it could be in use locally for one or more scopes. So it needs to be logged regardless of the global setting.

**Comment by gorhill** [comment] 2017-12-10 22:33
I am closing this because I don't believe there is still an issue.

uMatrix may still report that some cookies have been deleted even without the setting _"Delete cookies ..."_, because it listens to cookie deletion events, and this will be triggered regardless of how a cookie is deleted, including deleted by another extension or a by web page.

**Closed by gorhill** 2017-12-10 22:33 UTC
Labels: unable to reproduce
