### ISSUE TITLE
uMatrix causing Chrome errors for some HTTPS sites on corporate intranet

### ISSUE THREAD

**Issue by grepdashv** [gorhill/uMatrix#934] opened 2018-01-30 18:03 UTC
Chrome version: 64.0.3282.119
uMatrix version: 1.3.2

When visiting one particular site, Chrome returns the error "ERR_CONTENT_DECODING_FAILED".  When visiting a different particular site, Chrome returns the error "ERR_INVALID_RESPONSE".  Unfortunately, I cannot give further details about these sites as they are on a corporate intranet.  As far as I can tell, the sites are not using frames.

Looking at the logger, there are no blocked items.
No per-scope switches are enabled.
The intranet domain has been whitelisted.
Bypassing the cache does not work.
Disabling filtering for the domain scope does not work.
Filtering for behind-the-scene scope has not been enabled.
Turning off all spoofing/blocking options does not work.

Setting disableCSPReportInjection to true DOES allow the sites to load, so apparently the root cause is something to do with that injection.

**Comment by gorhill** [comment] 2018-01-30 18:41
Duplicate of #912.

**Closed by gorhill** 2018-01-30 18:41 UTC
Labels: duplicate

**Comment by gorhill** [comment] 2018-01-30 18:42
Why open a duplicate?

**Comment by grepdashv** [comment] 2018-01-30 18:51
While the workaround (disabling injection) is the same, the symptoms are different.  The title/scope of #912 does not apply to this issue (since no frames are involved), and it is possible that fixing #912 would not fix this issue.  If you're confident that fixing one would fix the other, then perhaps you could broaden the scope of #912 to include the fact that some HTTPS sites are unable to load and simply return Chrome errors (as opposed to showing a garbled page).

**Comment by gorhill** [comment] 2018-01-30 19:07
> to include the fact that some HTTPS sites are unable to load and simply return Chrome errors (as opposed to showing a garbled page)

This is out of uMatrix control, this is happening _inside_ the browser itself. uMatrix **merely** inject a CSP header through extensions APO, then from there this is in the hand of the browser. The browser parser is not something exposed to extensions.

**Comment by grepdashv** [comment] 2018-01-30 19:11
Ah, I see.  Sorry for the misunderstanding.  In any case, thanks for providing the option to disable that injection.
