### ISSUE TITLE
uMatrix 0.9.3.6 user-agent leak

### ISSUE THREAD

**Issue by kaliostro2** [gorhill/uMatrix#771] opened 2017-04-26 17:03 UTC
Just accidentally discovered the leak a real user-agent for which spoofing is responsible uMatrix.

In order to reproduce the leak it is necessary:

1: Go to https://mega.nz
2: Open about:config in new tab and change **dom.storage.enabled** to **false**
3: Go back to the tab with https://mega.nz and you will see a window with an error and your real user-agent.
<a href='https://hostingkartinok.com/show-image.php?id=d3da6d0a08a678cc483aa95114132616' title='фотохостинг'><img style="width:100%" src='https://s8.hostingkartinok.com/uploads/images/2017/04/d3da6d0a08a678cc483aa95114132616.png'  /></a>

- Windows 10 Enterprise x64 / Firefox 53 / uMatrix 0.9.3.6 (from MOA)
- I use 20 different user-agents from https://techblog.willshouse.com/2012/01/03/most-common-user-agents/
- Spoofing is always enabled and browserleaks.com shows that substitution occurred.
- Other addons do not affect the problem in any way. I tried the clean version of Firefox 53 on Windows 10 and Firefox 45 ESR on Debian Jessie 8.7.1. Installed only uMatrix from MOA. The result is the same. I even tried uMatrix 0.9.9b12 from MOA.

**Comment by gorhill** [comment] 2017-04-26 17:33
Unable to reproduce. Your report lacks information and **detailed** step-to-reproduce, so I went with my own steps:

- Using Linux, Firefox Nightly, uMatrix 1.0.0.
- Added `Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0` to the list of user agent strings in the _Privacy_ panel, commented out all other strings.
- Set `dom.storage.enabled` to `false` in `about:config`.
- Opened `https://mega.nz/` in a new tab.
- Ensured that the switch "User agent spoofing" is enabled for that site.

Result, the site thinks I am using Firefox 45 on Windows:

![a](https://cloud.githubusercontent.com/assets/585534/25447773/711c2e84-2a84-11e7-9896-0c382396d003.png)

I will reopen if you make a better case that there is an issue. You failed to:
- provide OS/Browser/uMatrix version
- provide which user agent strings you are using for spoofing
- provide assurance that you actually verified that spoofing is enabled
- provide other information as to whether other extensions/browser settings may be interfering
- provide **detailed** step to reproduce

**Comment by kaliostro2** [comment] 2017-04-26 18:08
Please. Reopened. I described in more detail. For me, this issue is a heartbleeding.

**Comment by gorhill** [comment] 2017-04-26 18:42
Somebody else will have to investigate -- I can't investigate if I can't reproduce.

**Comment by gorhill** [comment] 2017-04-26 18:52
Ok, I reproduce on FF53. Strangely, I can't reproduce on Nightly.

**Comment by gorhill** [comment] 2017-04-26 19:04
The site's Content Security Policy does not allow inline script tags, this means uMatrix inline script tag to spoof window.navigator is not allowed to execute.

Unexpectedly, uMatrix's inline script works with Nightly. It's unclear whether the is by design or not, maybe Nightly allows inline script injected by extensions? (would make sense since they are trusted by the user).

**Comment by kaliostro2** [comment] 2017-04-26 19:52
I confirm. Firefox 55 does not have this issue. Firefox 54 and below are affected.

**Comment by gorhill** [comment] 2017-04-26 20:00
I have a fix, but it's best called a "mitigation", it will work for this site, but there is no guarantee it will work for some other site. it will work for this site because I created a fallback to `data:` URI to inject he script.

But in the end, the reality is that I am seriously considering removing UA spoofing, it gives a false impression of accomplishing somethign useful. Turns out countering fingerprinting has become quite an undertaking, and partially spoofing **some** navigator entries accomplish nothing -- I rather remove this clumsy feature borne out of experimental code years ago before I understood fully what was at stake.

See for yourself using dev console, inspect `window.navigator` for whichever site for which the UA spoofer seems to work. You will see other entries in there not touch by uMatrix and which contradict entries touched by uMatrix.

In the end, UA spoofing and all other anti-fingerprinting mechanisms are best left to a specialized extension, and that will require a lot of work, this does not belong to a network request firewall like uMatrix.

**Comment by kaliostro2** [comment] 2017-04-26 20:05
No.Please. Don`t remove UA Spoofing. I have not seen a good addon which could be given this job.

**Comment by gorhill** [comment] 2017-04-26 20:08
> No.Please. Don`t remove UA Spoofing.

It does not really prevent finding out which browser/OS you are using -- I rather remove it than mislead users into thinking the opposite.

**Comment by kaliostro2** [comment] 2017-04-26 20:09
:(

**Comment by kaliostro2** [comment] 2017-04-26 21:39
Tested all the add-ons specializing in UA Spoofing. They all have the above problem. I ask you to reconsider your decision and find a solution to the problem. I certainly understand that your main direction is uBlock Origin but still. Please forgive me for persistence.

**Comment by gorhill** [comment] 2017-04-26 22:48
The fix is in v1.0.1b0 on AMO dev channel.

**Comment by Atavic** [comment] 2017-04-27 19:02
Related: https://github.com/ghacksuserjs/ghacks-user.js/issues/5#issuecomment-280872100

**Comment by gorhill** [comment] 2017-04-28 11:18
@Atavic Here is about user agent spoofing, what you linked to is about referrer spoofing. Can you open a new issue for this, with a reference to the [blog post](https://feeding.cloud.geek.nz/posts/tweaking-referrer-for-privacy-in-firefox/) arguing why stripping out is better?

**Comment by Atavic** [comment] 2017-04-28 19:52
@gorhill Sure.

**Comment by Thorin-Oakenpants** [comment] 2017-05-03 10:20
I'm sure you are aware, that `privacy.resistFingerprinting`, as part of the Tor Uplift Project, will (hopefully) spoof UA. That ticket, will also hopefully close a few navigator and other holes. This is to *lower* entropy, and will only work in large numbers (and FF's base with that pref can do that) - the idea is to spoof as the latest ESR as per TBB does (i.e not claiming to be chrome or something silly).

Ref:
https://bugzilla.mozilla.org/show_bug.cgi?id=1333651
https://bugzilla.mozilla.org/show_bug.cgi?id=1333933

I wholeheartedly endorse that you drop the whole UA part for all the reasons you said. An earlier issue I raised (2 years ago?) was that JS did not match headers (fixed at the time by using UA JS Fixer or something add-on). Another issue raised by someone else was the real navigator values being leaked over iframes. The list goes on. There are so many "holes" and methods that add bits and raise entropy. I fully agree that this is left to a specialized extension and/or the Tor Uplift.

Just my 2cents :)

**Comment by SamHasler** [comment] 2017-11-22 10:02
>  partially spoofing some navigator entries does not accomplish much ...
> 
> See for yourself using dev console, inspect window.navigator for whichever site for which the UA spoofer seems to work. You will see other entries in there not touched by uMatrix and which contradict entries touched by uMatrix.

This is likely giving additional information with which to fingerprint users. i.e. if they see different UA for different requests they could assume µMatrix is installed.

**Comment by Atavic** [comment] 2017-11-22 18:46
This is a common problem for every extension that tries to change the user-agent from inside the browser.

**Closed** 2017-12-01 13:22 UTC
