### ISSUE TITLE
Bring back preset rules

### ISSUE THREAD

**Issue by gorhill** [gorhill/uMatrix#30] opened 2014-11-01 14:53 UTC
In a different, more flexible form. For example, we want regions to be able to create their own rules, and for users to import community-contributed rules, with no dependency on the Github repository.

Not sure if I will wait for this before shipping though, it's a big item.

**Comment by jimbo1qaz** [comment] 2016-04-20 23:53
New idea: Some sites integrate with Google Drive or Github. Is it possible to "inherit" rules from other domains? So if a web-app integrates with Drive, you can have it inherit Google Drive privileges and communicate unhindered?

This is just an idea, I haven't fully thought it out yet (how it interacts with global or 1st-party rules, etc.)

**Comment by WagnerGMD** [comment] 2016-08-05 21:07
I believe too that uMatrix could be better. Like said a lot of website integrate YouTube (etc). So, via one click on the button, uMatrix should be eable to create (directly) the right rules for the media (etc). Only a few rules are enough.
It would be useful because one user simply need somtimes to create temporary rules. By default, it sould be temporary. After, the user confirm (save).
I block everything. Then, no I don't want to create a global rule like :
`* ytimg.com image allow`
Also, it will simplify the process when a user start from scratch. I think about regulary, since a very long time (>6 months). It could be nice as a new (or back ? Recipes ?) feature and perhaps gorhill the day to be brave is not far...

One example below :
```
malwaretips.com s.ytimg.com css allow
malwaretips.com ytimg.com image allow
malwaretips.com s.ytimg.com script allow
malwaretips.com www.youtube.com script allow
malwaretips.com www.youtube.com xhr allow
malwaretips.com www.youtube.com frame allow
malwaretips.com googlevideo.com xhr allow
malwaretips.com redirector.googlevideo.com * block
-----------------------------------------
## Comment 
## It's works fine
* * * block
* redirector.googlevideo.com * block
-----------------------------------------
```

**Comment by Penguin-Guru** [comment] 2017-01-27 01:17
I've been using an extension called Stylish lately to adjust C.S.S. It has a "style template" sharing interface that is very convenient since it is only two clicks and provides a nice preview. Perhaps this could provide a good reference? I have described what I imagine below. This would be designed for quick adjustments and sharing, not for bulk scope management. Bulk scope management is basically already provided by the "Options>My rules" page, although it might be useful to separate imported rules to be committed, at least temporarily.

A single button, perhaps left of Refresh in the drop-down, could open a dialogue or simply change the drop-down panel to review/edit the current scope before uploading. This would ensure users know what is being submitted, doubling as confirmation, and allow them to  add comments and name/describe the rule set.

For those installing, they could select from a list of names or use arrow buttons to preview the new rule set before applying and refreshing (one button). If rules are previewed in the normal matrix panel, comments could be displayed above, or floating below or to the side depending on the display size. This would allow users to read the notes, or any other non-matrix rule information without opening the settings menu; perhaps they should only display when previewing.

Theoretically, I don't think it would be necessary for templates to be explicitly named or described since the scope and rules would clearly identify them and comments could be used to indicate the rules' purpose. The only problem I imagine would be those rules for domains that have not yet been referenced by the active page, which would have to be added to the matrix for preview and might be a bit confusing. Realistically, I don't know how many users would properly comment their scopes so it might be worth providing a blank name field "## Name: " in the header to encourage good practice, or just requiring a name before uploading to be safe.

**Comment by gorhill** [comment] 2018-01-29 22:12
For translators:

![a](https://user-images.githubusercontent.com/585534/35537250-8cb26ba4-0517-11e8-940c-47f64067f158.png)

**Comment by TonnesM** [comment] 2018-01-30 15:48
@gorhill 
1. Are you sure you don’t need to invalidate the 3 additional (changed) ubiquitousRulesPageName, hostsFilesAutoUpdatePrompt & hostsFilesExternalListsHint strings for locales on Crowdin to to prevent them from remaining unnoticed?
2. While at it, can you please remember not to include trailing periods for option text strings such as "Auto-update assets" and fix it?

**Comment by uBlock-user** [comment] 2018-01-30 16:36
I'm seeing a new icon in the popup UI - https://i.gyazo.com/a05b63773ec7ffdf14aca126ea4b2627.png

But it doesn't have a tooltip defined. What is it ?

**Comment by uBlock-user** [comment] 2018-01-30 16:44
Nevermind, inspecting it reveals it's a button for the toggling recipe rules ? Seems you forgot to add the tooltip for that.

**Comment by TonnesM** [comment] 2018-01-30 16:51
> Do you know how this can be done without having to go through all translations?

Sorry I don’t know, not even with (temporary?) managing permissions. ;) Yet there must be some way to do this quickly.

Side note: in general, the period issue is also valid for tooltips.

**Comment by gorhill** [comment] 2018-01-30 17:19
> Seems you forgot to add the tooltip for that.

There is no tooltip for buttons which serve dropdown menus -- the tooltip would interfere with the content of the dropdown menu visually.

**Comment by mikhaelkh** [comment] 2018-01-30 20:46
@gorhill, can you clarify recipe syntax? The way I see it:
```
name
	source destination
		source destination [type [action]]
```
Recipe is shown if exists a request matching 2nd line.
If a rule with the same `source destination type` and different `action` already exists, it is not overwritten.  
`action` is always omitted in `uAssets/recipes/recipes_en.txt`, is it optional or always `allowed`?
Are global recipes (`source destination` = `* *`) allowed?

**Comment by gorhill** [comment] 2018-01-30 21:01
First line is name of ruleset recipe.

Second line is condition for recipe to be a hit:
- First must match source hostname (the current site's hostname).
- Second must match one of the destination hostname (one of the 3rd-party in the matrix).
- `*` means match any.

The rest of the lines are rules to be imported, **only as a per-need basis** (if internally the associated cell is blocked). `allow` is implicit (I didn't see the point yet to block more stuff on top of default -deny).

At this point this all need to be field tested for me to adjust as necessary.

**Comment by mikhaelkh** [comment] 2018-01-30 21:12
> I didn't see the point yet to block more stuff on top of default -deny.

1st-party requests are allowed by default, maybe sometimes it makes sense to block something, using `block` rule or [Per-scope-switch](https://github.com/gorhill/uMatrix/wiki/Per-scope-switches) rule.

**Comment by TonnesM** [comment] 2018-01-31 12:56
>  remove spurious trailing periods (#30 (comment)) 

Thanks for fixing those. Sorry for being picky while at it, but spurious periods probably also apply to matrixMtxButtonTip, matrixPersistButtonTip, matrixRevertButtonTip, (not matrixReloadButton as this has an additional line), privacyDeleteBlockedCookiesPrompt and statsPageLogSizePrompt2 (if still used).

Additionally, "Backup to file..." should probably be "Back up to file...", as with uBlock (verb intended).

**Comment by anewuser** [comment] 2018-02-06 19:33
@gorhill are you going to host only the English recipe, or are recipes for other languages also allowed? I've started this https://github.com/anewuser/uAssets/blob/patch-3/recipes/recipes_pt.txt

**Comment by gorhill** [comment] 2018-02-08 10:51
@anewuser @warnellw @ArchangeGabriel @pwd-github 

You have been contributing with ruleset recipes, and as I am trying to come up with clear guidelines about how recipes should be crafted, we should centralized here all the discussion about this. I have been thinking more about all this and with the feedback I changed my mind about some of what said before, including changes that I required. For now I roughly assembled ["Contributing ruleset recipes"](https://github.com/gorhill/uMatrix/wiki/Contributing-ruleset-recipes), feel free to discuss/comment/modify.

**Comment by ArchangeGabriel** [comment] 2018-02-08 11:22
This is almost perfect for me, the only thing I’m not sure about is this part:
```
_ somecdn.com *
_ somecdn.com script
_ somecdn.com frame
```
First, the role of `*` in this context is not clearly defined in my opinion, and second, I don’t understand if and then why if only scripts are need there should be an `*` rule. But maybe that’s because I don’t understand the `*` rule in the first place, which brings us back to my first point.

**Comment by gorhill** [comment] 2018-02-08 11:43
> I don’t understand if and then why if only scripts are need there should be an `*` rule

That's it, that is one of the point for which I changed my mind, hence the passage:

> For any given 3rd-party, if only one type of request is needed, then the rule should allow only that one specific type.

**Comment by ArchangeGabriel** [comment] 2018-02-08 14:28
Right, missed that this was stated above. So it clearly appears that I don’t understand the `*` rule, since I don’t see why allowing `xhr` and `script` at the same time would require an `*` rule technically. Doesn’t the `*` rule just imply that `image` and `css` are allowed?

**Comment by gorhill** [comment] 2018-02-08 14:52
> I don’t see why allowing `xhr` and `script` at the same time would require an `*` rule technically

To minimize ruleset. With out of the box rules, a rule with type `*` will be picked. Then the recipe manager will process the `script` rule, and when it sees that scripts are already allowed (because previous `*` rule), it will skip the rule. And so on for all following rules.

Consider:

    _ somecdn.com *
    _ somecdn.com script
    _ somecdn.com xhr

With out of the box ruleset, the recipe manager will just end up applying `_ somecdn.com * allow`, which will cause `script` and `xhr` to both become allowed. One single rule for both.

In the case where scripts are blocked everywhere by default, the recipe manager will end up applying `_ somecdn.com * allow` and `_ somecdn.com script allow`.

In the case where someone blocks all scripts and xhrs, then there will be three rules applied, but I expect that sort of cases to be an edge one, and whoever confirgure uMatrix like this is probably less likely to need the help of recipes to unbreak sites.

**Comment by ArchangeGabriel** [comment] 2018-02-08 14:57
OK, make sense to me now. I think this means I should change my rules from:
```
* 1st-party cookie block
* 1st-party script block
```
to:
```
* * cookie block
* * script block
```
if I intend to use preset rules (my understanding being that using preset rules would help reducing the size of my custom rules).

**Comment by warnellw** [comment] 2018-02-08 15:28
@ArchangeGabriel 

> Doesn’t the * rule just imply that image and css are allowed?

I've considered this the absolute minimum when creating recipes. That is, I assume someone with a very strict ruleset would still globally allow CSS/images (which the * would cover at a bare minimum, and no other resources).

That being said, my personal ruleset disallows all 3rd party resources, including CSS/images. I've noticed trackers (e.g. DoubleClick) use images for pixel tracking, so I now consider all 3rd party resources hostile.

**Comment by gorhill** [comment] 2018-02-09 14:21
Need a tool to one-click snapshot the rules in current popup panel into a temporary recipe in a sort of scratchpad which can then be edited/tested on the spot. The current way of creating/testing recipes is tedious.

**Comment by pwd-github** [comment] 2018-02-09 17:11
This looks good for me. I'm interested in the global rulesets though. Especially for Decentraleyes.

**Comment by Two-Finger** [comment] 2018-02-10 14:37
A small enhancement proposal.

* The puzzle-piece menu currently offers no way to *disable* a recipe. One must open the Dashboard, find all the entries involved and delete them. It would be nice if we could toggle a recipe on and off straight from the menu.
* The padlock buttons next to recipes names are redundant, since the changes are immediately reflected in the global padlock button and it could be used instead.

**Comment by gorhill** [comment] 2018-02-10 14:52
> offers no way to disable a recipe

Recipes are not an on/off thing, it's a set of rules which are **imported** into your own ruleset. You may have already some `allow` rules which are meant to be toggled on by the recipe, so of course it would be bad if uMatrix was removing rules you already had set on your side before importing the recipes.

> padlock buttons next to recipes names are redundant

They are not. Some recipes may import rules which are not visible in the current scope, and without that extra padlock it would be impossible to easily save these out of view rules.

The purpose of recipes is that of convenience, to easily **import** rulesets -- they must _not_ be seen as more than this. Users are still completely responsible for whatever rules they agree to import as part of their own ruleset.

**Comment by pwd-github** [comment] 2018-02-11 14:17
Just a heads up: The jigsaw piece hasn't got a tooltip yet.

**Comment by pwd-github** [comment] 2018-02-11 14:38
Having had a chance to play around properly. I noticed that we can import the rules into the temporary ruleset and then we have to click the padlock to save the rules, that's awesome. It allows us to the tweak the rules to our own needs and that's literally perfect. However once the recipes are imported, there's no way to undo as the eraser doesn't become highlighted. Not so awesome. 

And just to add to what I said before, about global rulesets. My reasoning is best demonstrated with Decentraleyes
```
Decentraleyes
 	*
 	 	* cdn.madeupsite.com script allow
 	 	* cdn.madeupsite2.com script allow
```
Now I note that in @warnellw's pull request, @gorhill says that he doesn't believe users should necessarily configure uMatrix for Decentraleyes or via versa, but I'd argue that we're essentially unbreaking the internet for uMatrix users which is essentially Decentraleyes does given the sheer amount of linked everything in webpages these days. I think it's important that users that care, are in a position where they can one-click allow a bunch of CDNs without compromising their privacy. Which brings me to my segue, that's all on the allow side, I'd also like to see something on the block side, as I know I block a bunch of sites wherever possible including google's sites. So if there was a tracking blocklist for the main offenders that I could import via the jigsaw, I'd love that too.
```
PWD privacy list
 	*
 	 	* google-analytics.com * block
 	 	* googletagmanager.com * block
 	 	* histats.com * block
```
Now the argument would be that those are already covered by the existing hostfiles, but the issue is that you have no control over them. It's like an all of nothing on a massively large scale.

Anyway, even I've not thought of how to implement it properly, so it's just food for thought at this point in time.

**Comment by aleksejrs** [comment] 2018-03-21 07:27
Where do I put my recipes written according to https://github.com/gorhill/uMatrix/wiki/Contributing-ruleset-recipes so that they appear under the puzzle button?

**Comment by ArchangeGabriel** [comment] 2018-03-28 12:35
@aleksejrs: https://github.com/uBlockOrigin/uAssets/tree/master/recipes

**Comment by aleksejrs** [comment] 2018-04-02 10:28
@ArchangeGabriel Actually, there is an "Import" control in the Preferences, which accepts one URL per line. It adds the specified file when I press the Apply button, but the "Import" checkbox becomes unchecked, the field disappears and the list is lost, so while using Firefox in an unfamiliar language, I thought it was the Undo button.

**Comment by gorhill** [comment] 2018-04-02 10:35
@aleksejrs Firefox does not allow extensions to read from `file:///` URLs. I suggest you create a Gist and import its URL, that should work. Another option is to enable the advanced setting `contributorMode`, this will add a textarea widget in the Assets pane which purpose is to add inline recipes.

**Comment by eren-kemer** [comment] 2018-04-02 14:40
It seems like the recipe is not updating with the update now button?
![firefox_2018-04-02_16-36-03](https://user-images.githubusercontent.com/4806188/38200302-5268f8d0-3683-11e8-8942-8337aea546d8.png)
I have updated the list and manually checked the current master version and my version (youtube specifically)
Note that both versions have the version 1.0
My version:
![firefox_2018-04-02_16-38-15](https://user-images.githubusercontent.com/4806188/38200361-8062bf32-3683-11e8-8d9b-6b2442a213f2.png)

Version at https://github.com/uBlockOrigin/uAssets/blob/master/recipes/recipes_en.txt : 
![firefox_2018-04-02_16-39-16](https://user-images.githubusercontent.com/4806188/38200395-ad26f27c-3683-11e8-87bf-12cf7f3c2ebe.png)

Is this possibly because of the version staying the same?
Or is updating of those recipes not implemented correctly yet?

**Comment by gorhill** [comment] 2018-04-02 15:35
> My version:

How did you look at the content of your version?

**Comment by vanfumin08** [comment] 2018-04-02 15:41
---------- Forwarded message ---------

**Comment by eren-kemer** [comment] 2018-04-02 15:43
I went to uMatrix Settings > Assets > Clicked on 'Ruleset recipes for English websites​​​​​'.
Which is essentially a link to 'moz-extension://69111b79-a6da-48be-84ef-a1ddab966d86/asset-viewer.html?url=recipes_en-0'
On the top it says
```
! uMatrix: Ruleset recipes 1.0 
! Title: Rulesets for English websites 
! Maintainer: uMatrix
```

While the latest version also says 1.0:
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/recipes/recipes_en.txt

**Comment by gorhill** [comment] 2018-04-02 15:52
I don't change the version -- it's for the parser to use, it will stay the same unless the format of the recipes change.

**Comment by eren-kemer** [comment] 2018-04-02 16:49
Shouldn't "update now" pull the newest changes though?

**Closed as completed** 2018-04-15 13:20 UTC
