### ISSUE TITLE
IPv6 rules are not saved across restarts and not properly applied

### ISSUE THREAD

**Issue by TerraX-net** [gorhill/uMatrix#747] opened 2017-03-30 12:52 UTC
![umatrix-ipv6](https://cloud.githubusercontent.com/assets/17962859/24504750/bc6e2672-1557-11e7-89c8-4dcc394748a8.png)
We should see the login page here. If I turn the red 3rd-party scripts to green, the three 1st party scripts are getting loaded and we can see everything.
When I press the padlock to save this (weird) rule, this one is under permanent rules:
chrome://umatrix/content/dashboard.html#user-rules
[fd00::9ec7:a6ff:fe70:cb36] * script allow

Then I restart the browser and visit this url again, the host-specific rules are not applied. I only have this default settings again. The permanent rule is gone.

Only the following permanent rule is saved acress browser restarts, but I don't want to have such a rule:
matrix-off: [fd00::9ec7:a6ff:fe70:cb36] true

The bugs are
- IPv6-host-specific rules are not saved across browser restarts
- 1st-party rules are not applied. Every script is a 3rd-party script, even if it's a 1st party one.

**Comment by xofe** [comment] 2017-03-31 08:16
Duplicate of #597. This should be fixed in the dev build, if you're willing to try that out.

**Comment by TerraX-net** [comment] 2017-03-31 10:32
> IPv6-host-specific rules are not saved across browser restarts

not fixed! The rule I've set is still lost over a restart. Can you reproduce this?

> 1st-party rules are not applied. Every script is a 3rd-party script, even if it's a 1st party one.

fixed in the pre-release

**Comment by xofe** [comment] 2017-03-31 11:45
> not fixed! The rule I've set is still lost over a restart. Can you reproduce this?

Ah, I can reproduce this. Looks like the `[fd00::9ec7:a6ff:fe70:cb36] * script allow` rule is [mistakenly considered an unknown directive](https://github.com/gorhill/uMatrix/blob/master/src/js/matrix.js#L771) (due to the `:` character in hostname) and therefore ignored.

**Closed** 2017-04-01 14:06 UTC
