### ISSUE TITLE
blocks content even when disabled

### ISSUE THREAD

**Issue by algazarra** [gorhill/uMatrix#238] opened 2015-05-29 14:37 UTC
even when disabled, uMatrix is blocking TV's (tradingview.com) charts from opening. It even blocks chart's thumbnails being shared on the chat. Why is it blocking even when disabled?

**Comment by gorhill** [comment] 2015-05-29 14:55
Unable to reproduce. No details provided. Will close after one day of no details steps/observations of how to reproduce, detailed information about settings.

**Comment by gorhill** [comment] 2015-05-29 15:01
Actually, closing, this makes no sense, when uMatrix is disabled it is not even running.

**Comment by algazarra** [comment] 2015-05-29 15:16
what? you have no respect for the issue I submitted? and you give 15mins to reply? are you loco bro?
I'm on google chrome on ubuntu, I installed and disabled umatrix (on the power button) and it still blocks content.

**Comment by gorhill** [comment] 2015-05-29 15:24
> you have no respect for the issue I submitted?

I have something regarding respect in [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md), point 5. and 6.

> disabled umatrix (on the power button)

Ok, a bit more info. Still you do not provide any further details. What is blocked? Use the logger, it's the tool to use before filing reports, and to use to file report.

**Comment by algazarra** [comment] 2015-05-29 15:50
Ahhh now I see. You couldn't replicate the problem cause I had contacted the website's admin about this issue. He had already replied and solved the issue.

I'm curious though. What could cause the chart's block if I had uMatrix disabled?

**Comment by algazarra** [comment] 2015-05-29 16:03
No! problem persists... have no idea how to use the logger.

Go to tradingview.com
open the chat (you won't see any published charts there so you won't notice they're blocked)
try opening any shared charts inside the chat

**Comment by gorhill** [comment] 2015-05-29 16:15
> open the chat

- I disabled matrix filtering
- I opened uMatrix's logger
- I opened <https://www.tradingview.com/chat/#general>
    - Please provide a URL next time so that I do not have to guess it
- I clicked on a chart
    - The chart opened in another tab as a PNG image
- At no time did the logger report anything being blocked.
- I disable uMatrix in the browser
- I reload the page, and could not see any difference with before

**Comment by CrisBRM** [comment] 2015-05-29 16:33
@gorhill Can confirm. Wasn't working with uMatrix on (in default deny mode), disabled it and it worked. Chart opened in another tab. At no point did the logger report anything being blocked.

**Comment by algazarra** [comment] 2015-05-29 16:33
@gorhill I'm confused
Just activated uMatrix and now charts are working again.

I've been submitting issues to trading view devs. They've been making changes as we speak. Let me get back to you if problem persists. I believe the problem is not on uMatrix side.

BTW, what could be the reason for the charts being blocked even when uMatrix is disabled? TY

**Comment by gorhill** [comment] 2015-05-29 16:49
> what could be the reason for the charts being blocked even when uMatrix is disabled?

Strict HTTPS could be a reason.

**Comment by algazarra** [comment] 2015-05-29 17:05
> Strict HTTPS could be a reason.
I'm using HTTPS Everywhere

**Comment by gorhill** [comment] 2015-05-29 17:19
> maybe consider removing the unable to reproduce tag

Of course not, I really wasn't able to reproduce. Since you say the issue was on the web site's side, I will close.

**Closed by gorhill** 2015-05-29 17:19 UTC
Labels: unable to reproduce
