### ISSUE TITLE
Cannot "always allow" image and css for 1st-party

### ISSUE THREAD

**Issue by irgendsontyp** [gorhill/uMatrix#959] opened 2018-02-21 20:47 UTC
I want to allow image and css for every 1st-party site. I do **not** want to enable those for **every** web page because I do not want someone to silently make me load a tracking image.

When I select the "*"-scope in uMatrix, click in the rectangles for image and css so their backgrounds turn to green, css and image is still blocked (and have red background) on pages which I did not explicitely allow to load those resources.

Am I getting something wrong?

**Comment by Thorin-Oakenpants** [comment] 2018-02-22 03:26
Here is my `*` scope settings - note the far left `first party` is green
![scopeall](https://user-images.githubusercontent.com/16656956/36518351-fa158cf8-177d-11e8-9933-671971d717c8.png)

Now  every site will load 1st party css + images only as per the sections I boxed in black
![scopedomain](https://user-images.githubusercontent.com/16656956/36518470-69afa616-177e-11e8-9d9e-438754e98cc9.png)

Note: this works for me since I block everything else (top row `all`) and still alows me to control JS, cookies, frames etc even on 1st party

Here are a couple of examples of sites with no other changes
![examples](https://user-images.githubusercontent.com/16656956/36518827-00dd5078-1780-11e8-8414-c08907ea59eb.png)

**Comment by irgendsontyp** [comment] 2018-02-22 10:31
That's a nice workaround I will use, thank you very much!

Nevertheless, the issue I described is a bug, isn't it?

**Comment by gorhill** [comment] 2018-02-22 11:39
@irgendsontyp Your issue is invalid: you fail to provide detailed steps to reproduce. It's impossible to say anything. Marking as invalid until you actually make the case that there is an issue with uMatrix through detailed steps to reproduce.

Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2018-02-22 11:39 UTC
Labels: invalid

**Comment by Thorin-Oakenpants** [comment] 2018-02-23 04:17
> That's a nice workaround ...

Its not a workaround, it's working *exactly* as it is meant to

**Comment by WagnerGMD** [comment] 2018-02-24 02:57
If you don't want to use the uMatrix GUI, you can these rules :
```
* 1st-party css allow
* 1st-party image allow
```
From my point of view too, it won't be a bug neither a workaround. Because apparently no you aren't familiar with uMatrix.
