### ISSUE TITLE
Videos not working on Youtube with referrer spoofing enabled

### ISSUE THREAD

**Issue by Greed1** [gorhill/uMatrix#373] opened 2015-10-10 11:54 UTC
Hi,

Since I updated Umatrix from 0.9.2.1 to 0.9.3.0, the videos on youtube aren't working anymore. It only occurs when referrer spoofing is  enabled.
Everything was working well with 0.9.2.1

I'm using Firefox 41.0.2

Thanks.

**Comment by gorhill** [comment] 2015-10-10 11:57
Duplicate of #358.

**Closed by gorhill** 2015-10-10 11:57 UTC
