### ISSUE TITLE
Icons not displayed in pulldown menu

### ISSUE THREAD

**Issue by neosol** [gorhill/uMatrix#792] opened 2017-05-25 12:16 UTC
I‘ve set browser.display.use_document_fonts to 0 (in about:config of firefox) because of privacy reasons.
Set this way when opening the umatrix pulldown menu part of the icons will not be displayed correctly.
Is a fix for this cosmetic issue possible?

**Comment by gorhill** [comment] 2017-05-25 12:33
Duplicate of #227.

**Closed by gorhill** 2017-05-25 12:33 UTC
