### ISSUE TITLE
Migrate user backup/restore functionality to 'Settings' tab

### ISSUE THREAD

**Issue by glitsj16** [gorhill/uMatrix#714] opened 2017-02-20 21:29 UTC
Hi, I wonder if you'd consider putting the user backup/restore functionality under the 'Settings' tab (cfr. uBlock). As it currently resides under the 'About' pane, it feels a bit out of place there. Just a cosmetic suggestion/question, functionality itself works just fine here.

Regards

**Comment by weflower** [comment] 2017-11-14 02:49
I was just about to open a similar thread. It's not a big deal but it would be nice if uBlock and uMatrix were consistent with backup/restore buttons.

**Comment by gorhill** [comment] 2017-11-20 19:17
Duplicate of #330.

**Closed by gorhill** 2017-11-20 19:17 UTC
Labels: duplicate
