### ISSUE TITLE
Allow to create "presets"

### ISSUE THREAD

**Issue by allo-** [gorhill/uMatrix#697] opened 2017-01-14 19:55 UTC
When i visit for example a site using disqus, i need three reloads until i can see the commands, as each iteration allows one layer of scripts to be loaded, which wasn't visible before. Now i do not want to permanantly whitelist this, so i need to do the procedure each time i want to see disqus comments.

I would like to be able to create a preset. This means, i select i.e. the 4 relevant rows and there current settings and then select "create preset 'disqus'". Next time i visit a site matching i.e. the first domain from the preset, i am offered the preset. 

When i activate it, i only need one reload and all sources included in the preset are allowed.
Such a disqus preset should not only match on the site where i created it, but on all sites using disqus comments, but should still need to be enabled in each scope separately.

**Comment by gorhill** [comment] 2017-01-14 20:38
Duplicate of #30.

**Closed by gorhill** 2017-01-14 20:38 UTC
