### ISSUE TITLE
Request: Extend blocking so individual scripts can be targeted rather than only by url..

### ISSUE THREAD

**Issue by Acecool** [gorhill/uMatrix#575] opened 2016-06-24 21:55 UTC
I visit a few sites frequently and have written quite a bit of JS to block certain systems from being effective, but it wouldn't even be necessary if we could block specific scripts from loading while allowing others...

Even if this becomes a separate addon, or an extension that'd fantastic! Not all scripts are malicious, but by blocking all indiscriminately it can disable other features such as live-search, etc... Being able to block specific scripts would add another layer to this already incredible and very useful extension...

**Comment by CrisBRM** [comment] 2016-06-24 23:28
Duplicate of https://github.com/gorhill/uMatrix/issues/574 as well as others.

>You can do this with uBlock. Disable a specific url, in this case, ending in .js, on a given hostname.

**Closed** 2016-06-25 12:57 UTC
Labels: duplicate

**Comment by Acecool** [comment] 2016-07-19 11:05
It is looking promising, but you can't blocks certain elements all the time... IE the one I'm trying to defeat is a very annoying system.. I've beaten all the old ones, now this one has a random div class ( Initial class-name is static so I tried removing that but Tampermonkey doesn't load quick enough for it to remove it ) and I rewrote the functions, classes, etc.. but as noted, tm doesn't load quick enough.

Also, it doesn't seem to support regex for blocking. I have a few elements I need to block which always follow a specific pattern ( div class starts static but hooked into 10 or so events plus timers, etc.. re-adds and renames it to a random 15 to 25 alphanumeric character string ), and some use link_[0-9]+ as the class-name but I can't target and adding for each specific link ( each link has its own id, so it isn't just 1, 2, 3, etc... )..

But, it does seem to be a lot more effective that Adblock plus.. Cheers.
