### ISSUE TITLE
Visual glitch when hostname is too long

### ISSUE THREAD

**Issue by user65478** [gorhill/uMatrix#383] opened 2015-10-17 19:23 UTC
Hi,

some hostnames are too long for uMatrix. Then they will not entirely fit into the table and will partially leak into the neighboring areas, like the following screenshot demonstrates: (notice the black spots between some cells):
![Image](http://fs5.directupload.net/images/151017/6ngsqwg9.png)

My browser: Firefox 41

Steps to reproduce (example):
1. Visit [focus.de](http://www.focus.de/)
2. Open uMatrix panel

**Comment by gorhill** [comment] 2015-10-17 20:03
Duplicate of #46.

**Closed by gorhill** 2015-10-17 20:03 UTC
