### ISSUE TITLE
Iframe and possibly other settings not reloading

### ISSUE THREAD

**Issue by JudasRose** [gorhill/uMatrix#812] opened 2017-11-14 19:22 UTC
Hi,

Not actually coding savvy but I'll try to explain the best I can what appears to be a bug. I noticed when i white listed sites through this addon some of the settings would not apply when I refreshed the page but they would when I opened a completely new tab. As an example I was browsing the mozilla blog that had an embedded youtube video. Disabling and refreshing would not show it, but disabling and opening the site in a new tab would.

Refreshing the page:
![refresh](https://user-images.githubusercontent.com/10350358/32799855-db627f9e-c946-11e7-857d-0c6d045a5400.PNG)

and a new tab:
![newtab](https://user-images.githubusercontent.com/10350358/32799991-3198a29e-c947-11e7-9417-93fc8f28064a.PNG)

URL: https://blog.mozilla.org/blog/2017/11/14/introducing-firefox-quantum/

I notice some other issues have been closed with other people that this has happened too, but everything is off including strict https and spoofing. I also have no custom rulesets.

**Comment by gorhill** [comment] 2017-11-14 20:29
Force-reload using the shift key, to bypass the cache. If this works for you, please close this issue.

**Comment by JudasRose** [comment] 2017-11-14 20:32
Yep that did it. Is this just if it's an Iframe though or any type of change i need to do a force reload. Possible to just do that by default as an option?

**Comment by gorhill** [comment] 2017-11-14 20:32
I could not reproduce your issue anyways, so I will close as _unable to reproduce_. The assumption with uMatrix is that if something does not work and I can't reproduce, you will have to investigate fully on your side why it's not working.

**Closed by gorhill** 2017-11-14 20:32 UTC
Labels: unable to reproduce
