### ISSUE TITLE
svg files (image/svg+xml) are detected as plugin

### ISSUE THREAD

**Issue by bonanza123** [gorhill/uMatrix#592] opened 2016-07-15 08:23 UTC
I was browsing the mathworks.com website and saw in uMatrix some "plugins" being detected.
The uMatrix log then showed me that the following file has been detected as plugin:
```
10:17:45		--	plugin	http://de.mathworks.com/images/responsive/global/pic-header-mathworks-logo2.svg
```
is that correct? Or should it be detected as image?

The first few lines from wget show me:
```
wget -O /dev/stdout http://de.mathworks.com/images/responsive/global/pic-header-mathworks-logo2.svg                                                      :(
--2016-07-15 10:19:21--  http://de.mathworks.com/images/responsive/global/pic-header-mathworks-logo2.svg
Resolving de.mathworks.com (de.mathworks.com)... 184.31.86.199
Connecting to de.mathworks.com (de.mathworks.com)|184.31.86.199|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21091 (21K) [image/svg+xml]
Saving to: ‘/dev/stdout’

/dev/stdout                                                  0%[                                                                                                                                         ]       0  --.-KB/s               <?xml version="1.0" encoding="iso-8859-1"?>
<!-- Generator: Adobe Illustrator 17.0.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_2" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
         viewBox="0 0 167 34" style="enable-background:new 0 0 167 34;" xml:space="preserve">
```

**Comment by gorhill** [comment] 2016-07-15 10:31
Key basic information missing: browser version/uMatrix version. Will assume invalid entry until proper information is provided.

**Comment by bonanza123** [comment] 2016-07-15 16:23
@gorhill  sorry for the missing information. I hope here is everything that is needed:

The browsed website: http://de.mathworks.com/
Firefox version 47.0.1
uMatrix version 0.9.3.6

**Comment by gorhill** [comment] 2016-07-16 11:05
Somebody posted on Wilder Security that this was happening on Amazon. I can reproduce with front page `https://www.amazon.com/`, in botu uMatrix and uBlock.

**Comment by gorhill** [comment] 2016-07-16 11:34
Turns out Firefox Nightly also reports network requests of type `object` in the dev console:

![a](https://cloud.githubusercontent.com/assets/585534/16894532/30dd5240-4b27-11e6-8310-6bae346e9128.png)

This means uBlock/uMatrix is functioning properly. As to why these network requests exist at all, I have no clue. They all appear to be duplicate of earlier network requests  which were properly typed:

![a](https://cloud.githubusercontent.com/assets/585534/16894548/997cbda4-4b27-11e6-9d68-af41f0fc2ee8.png)

Thus uBO/uMatrix are just reporting what they see, the question now is to FF devs: why these duplicate network requests of type `object` (which uMatrix reports as `plugins`).

**Closed by gorhill** 2016-07-16 11:34 UTC

**Comment by gorhill** [comment] 2016-07-16 11:37
I also verified that ABP also reports these `object` requests. Adguard appears to report them also, but as `media` requests.

**Comment by Radagast** [comment] 2016-07-16 23:56
Is this Windows specific? For me, on Linux, with the exception of the 'svg' image on the MathWorks site, which has the type 'object' everything seems to be displayed/logged correctly.

![am] (http://imgur.com/fWMpNA1)

**Comment by stryx** [comment] 2017-01-09 18:56
There are many ways to include SVG-images in web-pages: as `<img>`, `<object>`, as a background image in CSS, data-uri, `<iframe>`, … It seems that depending on the way it is included, SVG images may appear in different columns in uMatrix. From a user-perspective this is not quite intuitive. But I'm not sure if this should be considered a bug. If so, it's probably not a good idea to blame the browser.

Concerning the documentation on MDN linked above

> [1] Type 5 as seen on [this reference documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIContentPolicy#Constants).

it is interesting to note that it says “Indicates a generic `object` (plugin-handled content typically falls under this category).” I guess this should be read with emphasis on “_typically_”. If this is the information uMatrix uses to determine the columns, the column name should be changed from “plugin” to “object”.

Since I haven't installed any plugins, it was quite disturbing for me as recently my online banking web page issued strange error messages after uMatrix had blocked content classified as “plugin”.
