### ISSUE TITLE
Feature Request: Templates

### ISSUE THREAD

**Issue by arvedarved** [gorhill/uMatrix#700] opened 2017-01-22 14:54 UTC
It would be handy to be able to define templates for sites that use certain external scripts e.g.

"allow Google Recapture": 
"allow embedded Youtube videos": 
"Allow embedded Google maps"
etc.etc.

Lots of sites use these, and I always have to make the same custom rules.

**Comment by gorhill** [comment] 2017-01-22 14:55
Duplicate of #30.

**Closed by gorhill** 2017-01-22 14:55 UTC
Labels: duplicate
