### ISSUE TITLE
Mishmash chars on page after login via "WWW-Authenticate: Basic realm" (chrome)

### ISSUE THREAD

**Issue by Monter** [gorhill/uMatrix#907] opened 2018-01-07 19:54 UTC
On websites with logging in using the "WWW-Authenticate: Basic realm" method, after logging in, the page displays a mix of characters. To display the correct content you need to refresh the page.
The problem occurs in a plug-in that is newer than version 1.2.0.

**Comment by gorhill** [comment] 2018-01-07 20:05
Closing and marking as _invalid_, as per [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2018-01-07 20:05 UTC
Labels: invalid

**Comment by Monter** [comment] 2018-01-07 20:56
I can not paste your website here, its address or screenshots because I did not protect it from access to show what is on it. i To repeat the problem to any PHP page, add the header "WWW-Authenticate: Basic realm" and the request for login and password - when you enter it, the page will open, but instead of the content will be random characters. After refreshing F5, the content is already correct. All new versions have this problem, v1.1.20 works correctly.

Everywhere you write that you do not have time. If you do not have it, do not make new versions with errors.

**Comment by gorhill** [comment] 2018-01-07 21:25
I need reproducible steps. Yours are quite demanding. Since you can reproduce on your side, best would be you investigate the issue. It's not necessarily uMatrix, you should test with other extensions which also modify the sent and received headers -- this could show that the issue is not specific to uMatrix. Bottom line, please contribute by investigating further the issue you see.

**Comment by Monter** [comment] 2018-01-07 22:08
Try https://ha-os.net/umatrix_test/
test:test

**Comment by chdh** [comment] 2018-01-28 16:26
The error only occurs when the authentication challenge response (with status code 401 and "WWW-Authenticate" header field) is uncompressed and the final response is compressed.

There is a [Chromium bug entry](https://bugs.chromium.org/p/chromium/issues/detail?id=801237) for the same problem.
