### ISSUE TITLE
[Feature Request] Add support for local hosts files

### ISSUE THREAD

**Issue by geplus** [gorhill/uMatrix#482] opened 2016-02-07 12:59 UTC
Hi, 
I think it could be nice & useful if uMatrix will implement the support for local hosts files, stored in your hard disk.
It could be useful for example using the Tor browser, that is not synchronized with the /etc/hosts file, for people that use their personal host file.
Whit this function, users could also import their pesonal host files from a folder.

**Comment by anewuser** [comment] 2017-11-15 23:05
Firefox extensions may no longer access local files. Please close this.

**Comment by gorhill** [comment] 2017-12-16 18:54
You can import `file:///` URLs with Chromium.

You can't (at least yet) with Firefox -- there is an issue on bugzilla about this.

**Closed by gorhill** 2017-12-16 18:54 UTC
Labels: browser bug

**Comment by gorhill** [comment] 2017-12-16 18:58
Duplicate of #302.
