### ISSUE TITLE
IPv6 [::1] scripts/stylesheets

### ISSUE THREAD

**Issue by TriMoon** [gorhill/uMatrix#736] opened 2017-03-22 15:31 UTC
Somehow uMatrix prevents scripts and stylesheets to be used on my [::1] address.
They work when having `[::1] * * allow` in the rules, eg. clicking the allow part in the "all" collumn while [::1] is selected.

**Comment by gorhill** [comment] 2017-03-22 15:56
Closing as invalid, it's as if you did not read [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md) or chose to completely dismiss it. It's impossible for me to say anything since you do not provide any details about your relevant ruleset. I will re-open if you submit a proper issue report with all relevant details and step-to-reproduce as asked in [CONTRIBUTING](https://github.com/gorhill/uMatrix/blob/master/CONTRIBUTING.md).

**Closed by gorhill** 2017-03-22 15:56 UTC

**Comment by TriMoon** [comment] 2017-03-23 09:45
Ok, @gorhill  no need to get snappy on me....
If you want a debuggers detailed steps then i can provide it (Just ask for more details).
Here goes:
* Preperation:
  1. Setup Apache2 to answer on localhost IPv4 + IPv6, (_see the Apache2 documentation_)
  1. Create the **index.html** that will be served by it using any editor of your choice.
  1. Inside the **_index_** make use of stylesheet(s) and script(s) both in the `head` and `body` of the html
  1. Make sure you use [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) on these stylesheet(s) and script(s).
     * I made use of the command mentioned on [https://www.srihash.org/](https://www.srihash.org/).
     * Using that info I created the following script to ease generation of the needed hashes: (naming it `sri.sh`)
```bash
#!/usr/bin/env bash
#	v1.0 <description>.
#
#	(C) 2017+ ©TriMoon™
#	https://github.com/TriMoon
#	License: BY-NC 4.0
#	This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License.
#	https://creativecommons.org/licenses/by-nc/4.0/

# See:
#	https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
#	https://www.srihash.org/
if test $# -lt 1; then
	printf "%b\n" \
		"Usage:	$(basename $0)  <filename> <sha-hash algorithm>\n" \
		"Where <sha-hash algorithm> can be 256, 384, and 512" \
		"Default being 384"
else
	file="$1"
	hash="${2:-384}"
	sri=$(openssl dgst -sha${hash} -binary "${file}" | openssl base64 -A)
	printf "%s\n" \
		"sha${hash}-${sri}"
fi
#
# Editor modelines  -  https://www.wireshark.org/tools/modelines.html
#
# Local variables:
# c-basic-offset: 4
# tab-width: 4
# indent-tabs-mode: t
# End:
#
# vi: set shiftwidth=4 tabstop=4 noexpandtab:
# :indentSize=4:tabSize=4:noTabs=false:
#
```
----
* Testing uMatrix:
  1. Make sure apache2 is running using the _Preperation_ steps mentioned above.
  1. Now access the webpage using `[::1]/` in the urlbar.
     * Open the _Webdeveloper_ window while looking at this page.
     * Interesting tabs for our purpose are **console** and **network**.
  1. The stylesheet(s) and script(s) are not in use at this moment, due to an error mentioned in the console. _(At least on my side.)_<br/>In my case i saw the following line in the console, no idea why because the command to generate the hashes is correct:<br/>`None of the “sha512” hashes in the integrity attribute match the content of the subresource.`
     * I made use of 3 hashes per integrity tag 256 + 384 + 512 just to be safe in case the browser didn't support one or the other.
  1. Click the uMatrix icon to open the interface of uMatrix.
  1. Click in the top row **inside** the red "all" column on the left.
     * This will add a temporary `[::1] * * allow` rule to uMatrix.
  1. Click the "Reload page" icon **inside** the uMatrix interface.
  1. This time the stylesheet(s) and script(s) will be in use for the viewed page.
     * There will not be any error as mentioned above in the console.
----
So which bug(s) is/are going on here?
  1. SRI related:
     1. [x] Firefox does not properly support [SRI](http://caniuse.com/#feat=subresource-integrity). _(shows supported for me)_
     1. [ ] The openssl on debian9 generates faulty hashes for use in [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity).
  1. uMatrix related:
     1. [ ] uMatrix bypasses [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) checks in above setting.

**Comment by TriMoon** [comment] 2017-03-23 11:38
Another observation related to this issue: (from my side as a mind-note)
  * Seems i'm **not** getting the `None of the “sha512” hashes in the integrity attribute match the content of the subresource.` error when i **disable proxy** usage.
  * So i need to check why my **privoxy** config alters those retrieved contents...
